import json
import os

langs = {
    "ru": {
        "shifts_report": "Отчет по сменам (кассы)", "total_revenue_sales": "Общая выручка", "total_gross_profit": "Валовая прибыль", "sales_revenue": "Выручка от продаж", "expenses": "Расходы", "deducted_from_profit": "Вычтено из прибыли", "net_profit_final": "Чистая прибыль", "after_deductions": "После вычета расходов", "from_date": "С даты", "to_date": "По дату", "employee": "Сотрудник", "all_filter": "Все", "reset_filter": "Сброс", "time_duration": "Время / Продолжительность", "opening_cash_start": "Начальные наличные", "sales_details": "Детали продаж", "actual_closing": "Фактическое закрытие", "shortage_surplus": "Недостача / Излишек", "net_profit_margin": "Чистая прибыль", "profit_percentage": "Прибыль %", "status": "Статус", "unknown_emp": "Неизвестен", "opened_at": "Открыто:", "closed_at": "Закрыто:", "ongoing_shift": "В процессе...", "cash_emoji": "💵 Наличные:", "card_emoji": "💳 Карта:", "bank_emoji": "🏦 Банк:", "credit_emoji": "📝 Кредит:", "total_label": "Итого:", "matched_status": "Совпадает ✅", "shortage_label": "Недостача", "surplus_label": "Излишек", "shift_profit_margin": "Маржа прибыли смены", "open_status": "Открыта", "closed_status_badge": "Закрыта", "no_matching_shifts": "Нет подходящих записей смен", "preparing_report": "Подготовка...", "generating_pdf_invoice": "Создание счет-фактуры PDF..."
    },
    "ja": {
        "shifts_report": "シフトレポート (レジ)", "total_revenue_sales": "総売上", "total_gross_profit": "粗利", "sales_revenue": "売上収益", "expenses": "経費", "deducted_from_profit": "利益から控除", "net_profit_final": "最終純利益", "after_deductions": "経費控除後", "from_date": "開始日", "to_date": "終了日", "employee": "従業員", "all_filter": "全て", "reset_filter": "リセット", "time_duration": "時間 / 期間", "opening_cash_start": "開始時の現金", "sales_details": "販売詳細", "actual_closing": "実際の締め", "shortage_surplus": "不足 / 余剰", "net_profit_margin": "純利益", "profit_percentage": "利益率 %", "status": "ステータス", "unknown_emp": "不明", "opened_at": "開始:", "closed_at": "終了:", "ongoing_shift": "進行中...", "cash_emoji": "💵 現金:", "card_emoji": "💳 カード:", "bank_emoji": "🏦 銀行:", "credit_emoji": "📝 クレジット:", "total_label": "合計:", "matched_status": "一致 ✅", "shortage_label": "不足", "surplus_label": "余剰", "shift_profit_margin": "シフト利益率", "open_status": "オープン", "closed_status_badge": "クローズ", "no_matching_shifts": "該当するシフト記録がありません", "preparing_report": "準備中...", "generating_pdf_invoice": "PDFファイルを作成中..."
    },
    "es": {
        "shifts_report": "Reporte de Turnos (Cajas)", "total_revenue_sales": "Ingresos Totales", "total_gross_profit": "Ganancia Bruta", "sales_revenue": "Ingresos por Ventas", "expenses": "Gastos", "deducted_from_profit": "Deducido de Ganancias", "net_profit_final": "Ganancia Neta Final", "after_deductions": "Después de Deducir", "from_date": "Desde", "to_date": "Hasta", "employee": "Empleado", "all_filter": "Todos", "reset_filter": "Restablecer", "time_duration": "Tiempo / Duración", "opening_cash_start": "Caja de Apertura", "sales_details": "Detalles de Ventas", "actual_closing": "Cierre Real", "shortage_surplus": "Faltante / Sobrante", "net_profit_margin": "Ganancia Neta", "profit_percentage": "Ganancia %", "status": "Estado", "unknown_emp": "Desconocido", "opened_at": "Abierto:", "closed_at": "Cerrado:", "ongoing_shift": "En curso...", "cash_emoji": "💵 Efectivo:", "card_emoji": "💳 Tarjeta:", "bank_emoji": "🏦 Banco:", "credit_emoji": "📝 Crédito:", "total_label": "Total:", "matched_status": "Coincide ✅", "shortage_label": "Faltante", "surplus_label": "Sobrante", "shift_profit_margin": "Margen de Turno", "open_status": "Abierto", "closed_status_badge": "Cerrado", "no_matching_shifts": "No hay registros de turnos coincidentes", "preparing_report": "Preparando...", "generating_pdf_invoice": "Generando factura PDF..."
    },
    "tr": {
        "shifts_report": "Vardiya Raporu (Kasalar)", "total_revenue_sales": "Toplam Satış", "total_gross_profit": "Brüt Kar", "sales_revenue": "Satış Geliri", "expenses": "Giderler", "deducted_from_profit": "Kardan Düşülen", "net_profit_final": "Net Kar", "after_deductions": "Giderler Düşüldükten Sonra", "from_date": "Başlangıç Tarihi", "to_date": "Bitiş Tarihi", "employee": "Personel", "all_filter": "Tümü", "reset_filter": "Sıfırla", "time_duration": "Zaman / Süre", "opening_cash_start": "Açılış Kasası", "sales_details": "Satış Detayları", "actual_closing": "Gerçek Kapanış", "shortage_surplus": "Açık / Fazla", "net_profit_margin": "Net Kar", "profit_percentage": "Kar %", "status": "Durum", "unknown_emp": "Bilinmeyen", "opened_at": "Açılış:", "closed_at": "Kapanış:", "ongoing_shift": "Devam Ediyor...", "cash_emoji": "💵 Nakit:", "card_emoji": "💳 Kart:", "bank_emoji": "🏦 Banka:", "credit_emoji": "📝 Veresiye:", "total_label": "Toplam:", "matched_status": "Eşleşti ✅", "shortage_label": "Açık", "surplus_label": "Fazla", "shift_profit_margin": "Vardiya Kar Marjı", "open_status": "Açık", "closed_status_badge": "Kapalı", "no_matching_shifts": "Eşleşen vardiya kaydı yok", "preparing_report": "Hazırlanıyor...", "generating_pdf_invoice": "PDF faturası oluşturuluyor..."
    },
    "fr": {
        "shifts_report": "Rapport de Quarts (Caisses)", "total_revenue_sales": "Ventes Totales", "total_gross_profit": "Bénéfice Brut", "sales_revenue": "Revenus des Ventes", "expenses": "Dépenses", "deducted_from_profit": "Déduit du Bénéfice", "net_profit_final": "Bénéfice Net", "after_deductions": "Après Déductions", "from_date": "De la Date", "to_date": "À la Date", "employee": "Employé", "all_filter": "Tous", "reset_filter": "Réinitialiser", "time_duration": "Heure / Durée", "opening_cash_start": "Caisse d'Ouverture", "sales_details": "Détails des Ventes", "actual_closing": "Fermeture Réelle", "shortage_surplus": "Manque / Surplus", "net_profit_margin": "Bénéfice Net", "profit_percentage": "Bénéfice %", "status": "Statut", "unknown_emp": "Inconnu", "opened_at": "Ouvert:", "closed_at": "Fermé:", "ongoing_shift": "En cours...", "cash_emoji": "💵 Espèces:", "card_emoji": "💳 Carte:", "bank_emoji": "🏦 Banque:", "credit_emoji": "📝 Crédit:", "total_label": "Total:", "matched_status": "Correspondant ✅", "shortage_label": "Manque", "surplus_label": "Surplus", "shift_profit_margin": "Marge du Quart", "open_status": "Ouvert", "closed_status_badge": "Fermé", "no_matching_shifts": "Aucun registre de quart correspondant", "preparing_report": "Préparation...", "generating_pdf_invoice": "Génération de la facture PDF..."
    },
    "de": {
        "shifts_report": "Schichtbericht (Kasse)", "total_revenue_sales": "Gesamtumsatz", "total_gross_profit": "Bruttogewinn", "sales_revenue": "Umsatzerlöse", "expenses": "Ausgaben", "deducted_from_profit": "Vom Gewinn abgezogen", "net_profit_final": "Nettogewinn", "after_deductions": "Nach Abzügen", "from_date": "Vom Datum", "to_date": "Bis Datum", "employee": "Mitarbeiter", "all_filter": "Alle", "reset_filter": "Zurücksetzen", "time_duration": "Zeit / Dauer", "opening_cash_start": "Anfangskasse", "sales_details": "Verkaufsdetails", "actual_closing": "Tatsächlicher Abschluss", "shortage_surplus": "Fehlbetrag / Überschuss", "net_profit_margin": "Nettogewinn", "profit_percentage": "Gewinn %", "status": "Status", "unknown_emp": "Unbekannt", "opened_at": "Geöffnet:", "closed_at": "Geschlossen:", "ongoing_shift": "Laufend...", "cash_emoji": "💵 Bargeld:", "card_emoji": "💳 Karte:", "bank_emoji": "🏦 Bank:", "credit_emoji": "📝 Kredit:", "total_label": "Gesamt:", "matched_status": "Übereinstimmend ✅", "shortage_label": "Fehlbetrag", "surplus_label": "Überschuss", "shift_profit_margin": "Schicht-Gewinnmarge", "open_status": "Geöffnet", "closed_status_badge": "Geschlossen", "no_matching_shifts": "Keine passenden Schichtaufzeichnungen", "preparing_report": "In Vorbereitung...", "generating_pdf_invoice": "PDF-Rechnung wird erstellt..."
    },
    "pt": {
        "shifts_report": "Relatório de Turnos (Caixas)", "total_revenue_sales": "Vendas Totais", "total_gross_profit": "Lucro Bruto", "sales_revenue": "Receitas de Vendas", "expenses": "Despesas", "deducted_from_profit": "Deduzido do Lucro", "net_profit_final": "Lucro Líquido", "after_deductions": "Após Deduções", "from_date": "Da Data", "to_date": "Até a Data", "employee": "Funcionário", "all_filter": "Todos", "reset_filter": "Redefinir", "time_duration": "Tempo / Duração", "opening_cash_start": "Caixa Inicial", "sales_details": "Detalhes de Vendas", "actual_closing": "Fechamento Real", "shortage_surplus": "Falta / Sobra", "net_profit_margin": "Lucro Líquido", "profit_percentage": "Lucro %", "status": "Status", "unknown_emp": "Desconhecido", "opened_at": "Aberto:", "closed_at": "Fechado:", "ongoing_shift": "Em andamento...", "cash_emoji": "💵 Dinheiro:", "card_emoji": "💳 Cartão:", "bank_emoji": "🏦 Banco:", "credit_emoji": "📝 Crédito:", "total_label": "Total:", "matched_status": "Correto ✅", "shortage_label": "Falta", "surplus_label": "Sobra", "shift_profit_margin": "Margem de Lucro", "open_status": "Aberto", "closed_status_badge": "Fechado", "no_matching_shifts": "Nenhum registro de turno correspondente", "preparing_report": "Preparando...", "generating_pdf_invoice": "Gerando fatura em PDF..."
    },
    "pt-BR": {
        "shifts_report": "Relatório de Turnos (Caixas)", "total_revenue_sales": "Vendas Totais", "total_gross_profit": "Lucro Bruto", "sales_revenue": "Receitas de Vendas", "expenses": "Despesas", "deducted_from_profit": "Deduzido do Lucro", "net_profit_final": "Lucro Líquido", "after_deductions": "Após Deduções", "from_date": "Da Data", "to_date": "Até a Data", "employee": "Funcionário", "all_filter": "Todos", "reset_filter": "Redefinir", "time_duration": "Tempo / Duração", "opening_cash_start": "Caixa Inicial", "sales_details": "Detalhes de Vendas", "actual_closing": "Fechamento Real", "shortage_surplus": "Falta / Sobra", "net_profit_margin": "Lucro Líquido", "profit_percentage": "Lucro %", "status": "Status", "unknown_emp": "Desconhecido", "opened_at": "Aberto:", "closed_at": "Fechado:", "ongoing_shift": "Em andamento...", "cash_emoji": "💵 Dinheiro:", "card_emoji": "💳 Cartão:", "bank_emoji": "🏦 Banco:", "credit_emoji": "📝 Crédito:", "total_label": "Total:", "matched_status": "Correto ✅", "shortage_label": "Falta", "surplus_label": "Sobra", "shift_profit_margin": "Margem de Lucro", "open_status": "Aberto", "closed_status_badge": "Fechado", "no_matching_shifts": "Nenhum registro de turno correspondente", "preparing_report": "Preparando...", "generating_pdf_invoice": "Gerando fatura em PDF..."
    },
    "hr": {
        "shifts_report": "Izvješće o Smjenama (Blagajne)", "total_revenue_sales": "Ukupna Prodaja", "total_gross_profit": "Bruto Dobit", "sales_revenue": "Prihodi od Prodaje", "expenses": "Troškovi", "deducted_from_profit": "Oduzeto od Dobiti", "net_profit_final": "Neto Dobit", "after_deductions": "Nakon Odbitaka", "from_date": "Od Datuma", "to_date": "Do Datuma", "employee": "Zaposlenik", "all_filter": "Svi", "reset_filter": "Poništi", "time_duration": "Vrijeme / Trajanje", "opening_cash_start": "Početna Blagajna", "sales_details": "Detalji Prodaje", "actual_closing": "Stvarno Zatvaranje", "shortage_surplus": "Manjak / Višak", "net_profit_margin": "Neto Dobit", "profit_percentage": "Dobit %", "status": "Status", "unknown_emp": "Nepoznato", "opened_at": "Otvoreno:", "closed_at": "Zatvoreno:", "ongoing_shift": "U tijeku...", "cash_emoji": "💵 Gotovina:", "card_emoji": "💳 Kartica:", "bank_emoji": "🏦 Banka:", "credit_emoji": "📝 Kredit:", "total_label": "Ukupno:", "matched_status": "Odgovara ✅", "shortage_label": "Manjak", "surplus_label": "Višak", "shift_profit_margin": "Marža Smjene", "open_status": "Otvoreno", "closed_status_badge": "Zatvoreno", "no_matching_shifts": "Nema odgovarajućih zapisa o smjeni", "preparing_report": "Priprema...", "generating_pdf_invoice": "Generiranje PDF računa..."
    },
    "zh": {
        "shifts_report": "班次报告（收银机）", "total_revenue_sales": "总销售额", "total_gross_profit": "毛利润", "sales_revenue": "销售收入", "expenses": "费用", "deducted_from_profit": "利润中扣除", "net_profit_final": "最终净利润", "after_deductions": "扣除费用后", "from_date": "开始日期", "to_date": "结束日期", "employee": "员工", "all_filter": "全部", "reset_filter": "重置", "time_duration": "时间 / 时长", "opening_cash_start": "期初现金", "sales_details": "销售明细", "actual_closing": "实际结账", "shortage_surplus": "短缺 / 盈余", "net_profit_margin": "净利润", "profit_percentage": "利润百分比", "status": "状态", "unknown_emp": "未知", "opened_at": "开启：", "closed_at": "关闭：", "ongoing_shift": "进行中...", "cash_emoji": "💵 现金：", "card_emoji": "💳 银行卡：", "bank_emoji": "🏦 银行：", "credit_emoji": "📝 赊销：", "total_label": "总计：", "matched_status": "金额匹配 ✅", "shortage_label": "短缺", "surplus_label": "盈余", "shift_profit_margin": "班次利润率", "open_status": "已开启", "closed_status_badge": "已关闭", "no_matching_shifts": "没有匹配的班次记录", "preparing_report": "准备中...", "generating_pdf_invoice": "正在生成PDF发票文件..."
    }
}

for lang, mapping in langs.items():
    filepath = f"resources/lang/{lang}.json"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for k, v in mapping.items():
            # Override no matter what to fix the English ones
            data[k] = v
            
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        print(f"Updated {filepath}")

print("Fixed translations for all languages.")
