<?php

require __DIR__.'/vendor/autoload.php';

$appUrl = 'http://localhost/system';
$fullUrl = 'http://localhost/system/storage/1/image.jpg';

$path = parse_url($fullUrl, PHP_URL_PATH);
echo "Full: $fullUrl\n";
echo "Path: $path\n";

// Scenario: Online with wrong APP_URL
$onlineAppUrl = 'http://localhost/system'; // Configured wrong
$onlineFullUrl = 'http://localhost/system/storage/1/image.jpg'; // Generated by Spatie
// Browser is at http://tech-sys.online/system
// If we output $onlineFullUrl, image breaks (localhost).
// If we output parse_url($onlineFullUrl, PHP_URL_PATH) -> /system/storage/1/image.jpg
// Browser resolves /system/storage... relative to domain -> http://tech-sys.online/system/storage... -> WORKS!

echo "Fix confirmed: Convert to relative path.\n";
