import json
import os

translations = {
    "en": {
        "إضافة منتج جديد": "Add New Product",
        "منتج فعال": "Active Product",
        "البيانات الأساسية": "Basic Information",
        "اسم المنتج (عربي)": "Product Name (Arabic)",
        "مثال: شيبس ليز ملح": "Ex: Lays Chips Salt",
        "بحث في جوجل صور": "Search Google Images",
        "اسم المنتج (إنجليزي)": "Product Name (English)",
        "Ex: Lays Chips Salt": "Ex: Lays Chips Salt",
        "التصنيف": "Category",
        "-- اختر تصنيف --": "-- Select Category --",
        "الوصف": "Description",
        "الوحدة الأساسية (أصغر وحدة)": "Base Unit (Smallest Unit)",
        "صورة الوحدة": "Unit Image",
        "اسم الوحدة": "Unit Name",
        "قطعة": "Piece",
        "كيلو": "Kilogram",
        "علبة": "Box",
        "مخصص..": "Custom..",
        "سعر الشراء (للعبوة)": "Purchase Price (per pack)",
        "عدد القطع بالعبوة": "Pieces per Pack",
        "باركود الوحدة": "Unit Barcode",
        "تلقائي إذا فارغ": "Auto-generate if empty",
        "شراء": "Purchase",
        "بيع": "Sale",
        "سعر البيع": "Selling Price",
        "التكلفة (للقطعة)": "Cost (per piece)",
        "الربح %": "Profit %",
        "الضريبة المضافة": "Added Tax",
        "السعر مع الضريبة": "Price with Tax",
        "الوحدات الإضافية (كرتون، درزن...)": "Additional Units (Carton, Dozen...)",
        "إضافة وحدة": "Add Unit",
        "حد التنبيه للمخزون": "Stock Alert Limit",
        "حفظ المنتج": "Save Product",
        "كرتون": "Carton",
        "درزن": "Dozen",
        "شريط": "Strip",
        "اكتب الاسم": "Type Name",
        "التحويل": "Conversion",
        "الباركود": "Barcode",
        "التكلفة (آلي)": "Cost (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Please write the product name in Arabic first",
        "نبهني قبل X يوم": "Alert me before X days",
        "تعديل المنتج:": "Edit Product:",
        "فاتورة شراء جديدة": "New Purchase Invoice",
        "العودة": "Back",
        "المورد": "Supplier",
        "مورد جديد": "New Supplier",
        "ابحث عن مورد...": "Search for supplier...",
        "تاريخ وتوقيت الفاتورة": "Invoice Date & Time",
        "رقم الفاتورة (للمورد)": "Invoice Number (Supplier)",
        "مثال: INV-1001": "Ex: INV-1001",
        "قم بالبحث لإضافة منتجات": "Search to add products",
        "ملخص الدفع": "Payment Summary",
        "المجموع الفرعي:": "Subtotal:",
        "خصم إضافي": "Additional Discount",
        "الصافي النهائي:": "Final Net:",
        "المدفوعات": "Payments",
        "💰 نقدي": "💰 Cash",
        "💳 بطاقة": "💳 Card",
        "🏦 تحويل": "🏦 Bank Transfer",
        "المتبقي:": "Remaining:",
        "رصيد (لك):": "Credit (for you):",
        "متبقي (عليك):": "Balance (due):",
        "خالص (تم الدفع بالكامل)": "Paid (Settled)",
        "حفظ الفاتورة": "Save Invoice",
        "إضافة مورد جديد": "Add New Supplier",
        "الاسم *": "Name *",
        "الشركة": "Company",
        "حفظ وإضافة": "Save & Add",
        "إضافة منتج سريع": "Quick Product Add",
        "قريباً...": "Coming Soon...",
        "وحدات إضافية": "Additional Units",
        "أصغر وحدة": "Smallest Unit",
        "للمورد": "for Supplier",
        "خالص": "Paid",
        "أحجام/وحدات تقديم": "Sizes/Serving Units"
    },
    "fr": {
        "إضافة منتج جديد": "Ajouter un nouveau produit",
        "منتج فعال": "Produit actif",
        "البيانات الأساسية": "Informations de base",
        "اسم المنتج (عربي)": "Nom du produit (arabe)",
        "مثال: شيبس ليز ملح": "Ex: Chips Lays Sel",
        "بحث في جوجل صور": "Rechercher sur Google Images",
        "اسم المنتج (إنجليزي)": "Nom du produit (anglais)",
        "التصنيف": "Catégorie",
        "-- اختر تصنيف --": "-- Choisir une catégorie --",
        "الوصف": "Description",
        "الوحدة الأساسية (أصغر وحدة)": "Unité de base (plus petite unité)",
        "صورة الوحدة": "Image de l'unité",
        "اسم الوحدة": "Nom de l'unité",
        "قطعة": "Pièce",
        "كيلو": "Kilo",
        "علبة": "Boîte",
        "مخصص..": "Personnalisé..",
        "سعر الشراء (للعبوة)": "Prix d'achat (par paquet)",
        "عدد القطع بالعبوة": "Pièces par paquet",
        "باركود الوحدة": "Code-barres de l'unité",
        "تلقائي إذا فارغ": "Auto si vide",
        "شراء": "Achat",
        "بيع": "Vente",
        "سعر البيع": "Prix de vente",
        "التكلفة (للقطعة)": "Coût (par pièce)",
        "الربح %": "Profit %",
        "الضريبة المضافة": "TVA",
        "السعر مع الضريبة": "Prix avec TVA",
        "الوحدات الإضافية (كرتون، درزن...)": "Unités supplémentaires (Carton, Douzaine...)",
        "إضافة وحدة": "Ajouter une unité",
        "حد التنبيه للمخزون": "Alerte de stock",
        "حفظ المنتج": "Enregistrer le produit",
        "كرتون": "Carton",
        "درزن": "Douzaine",
        "شريط": "Bande",
        "اكتب الاسم": "Taper le nom",
        "التحويل": "Conversion",
        "الباركود": "Code-barres",
        "التكلفة (آلي)": "Coût (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Veuillez écrire le nom en arabe d'abord",
        "نبهني قبل X يوم": "Alerter X jours avant",
        "تعديل المنتج:": "Modifier le produit :",
        "فاتورة شراء جديدة": "Nouvelle facture d'achat",
        "العودة": "Retour",
        "المورد": "Fournisseur",
        "مورد جديد": "Nouveau fournisseur",
        "ابحث عن مورد...": "Rechercher un fournisseur...",
        "تاريخ وتوقيت الفاتورة": "Date et heure de la facture",
        "رقم الفاتورة (للمورد)": "Numéro de facture (Fournisseur)",
        "مثال: INV-1001": "Ex: INV-1001",
        "قم بالبحث لإضافة منتجات": "Rechercher pour ajouter des produits",
        "ملخص الدفع": "Résumé du paiement",
        "المجموع الفرعي:": "Sous-total :",
        "خصم إضافي": "Remise supplémentaire",
        "الصافي النهائي:": "Net final :",
        "المدفوعات": "Paiements",
        "💰 نقدي": "💰 Espèces",
        "💳 بطاقة": "💳 Carte",
        "🏦 تحويل": "🏦 Virement",
        "المتبقي:": "Reste :",
        "رصيد (لك):": "Crédit (pour vous) :",
        "متبقي (عليك):": "Solde (dû) :",
        "خالص (تم الدفع بالكامل)": "Payé (Solfé)",
        "حفظ الفاتورة": "Enregistrer la facture",
        "إضافة مورد جديد": "Ajouter fournisseur",
        "الاسم *": "Nom *",
        "الشركة": "Société",
        "حفظ وإضافة": "Enregistrer et ajouter",
        "إضافة منتج سريع": "Ajout rapide",
        "قريباً...": "Bientôt...",
        "وحدات إضافية": "Unités supplémentaires",
        "أصغر وحدة": "Plus petite unité",
        "خالص": "Payé",
        "أحجام/وحدات تقديم": "Tailles/Unités de service"
    },
    "tr": {
        "إضافة منتج جديد": "Yeni Ürün Ekle",
        "منتج فعال": "Aktif Ürün",
        "البيانات الأساسية": "Temel Bilgiler",
        "اسم المنتج (عربي)": "Ürün Adı (Arapça)",
        "مثال: شيبس ليز ملح": "Örn: Lays Cips Tuzlu",
        "بحث في جوجل صور": "Google Görsellerde Ara",
        "اسم المنتج (إنجليزي)": "Ürün Adı (İngilizce)",
        "التصنيف": "Kategori",
        "-- اختر تصنيف --": "-- Kategori Seç --",
        "الوصف": "Açıklama",
        "الوحدة الأساسية (أصغر وحدة)": "Temel Birim (En Küçük Birim)",
        "صورة الوحدة": "Birim Görseli",
        "اسم الوحدة": "Birim Adı",
        "قطعة": "Adet",
        "كيلو": "Kilo",
        "علبة": "Kutu",
        "مخصص..": "Özel..",
        "سعر الشراء (للعبوة)": "Alış Fiyatı (Paket Başı)",
        "عدد القطع بالعبوة": "Paketteki Adet",
        "باركود الوحدة": "Birim Barkodu",
        "تلقائي إذا فارغ": "Boşsa Otomatik Oluştur",
        "شراء": "Alış",
        "بيع": "Satış",
        "سعر البيع": "Satış Fiyatı",
        "التكلفة (للقطعة)": "Maliyet (Adet Başı)",
        "الربح %": "Kar %",
        "الضريبة المضافة": "KDV",
        "السعر مع الضريبة": "KDV Dahil Fiyat",
        "الوحدات الإضافية (كرتون، درزن...)": "Ek Birimler (Koli, Düzine...)",
        "إضافة وحدة": "Birim Ekle",
        "حد التنبيه للمخزون": "Stok Uyarı Limiti",
        "حفظ المنتج": "Ürünü Kaydet",
        "كرتون": "Koli",
        "درزن": "Düzine",
        "شريط": "Şerit",
        "اكتب الاسم": "İsim Yaz",
        "التحويل": "Dönüşüm",
        "الباركود": "Barkod",
        "التكلفة (آلي)": "Maliyet (Oto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Lütfen önce ürün adını Arapça yazın",
        "نبهني قبل X يوم": "X gün önce uyar",
        "تعديل المنتج:": "Ürünü Düzenle:",
        "فاتورة شراء جديدة": "Yeni Alış Faturası",
        "العودة": "Geri",
        "المورد": "Tedarikçi",
        "مورد جديد": "Yeni Tedarikçi",
        "ابحث عن مورد...": "Tedarikçi ara...",
        "تاريخ وتوقيت الفاتورة": "Fatura Tarihi ve Saati",
        "رقم الفاتورة (للمورد)": "Fatura No (Tedarikçi)",
        "مثال: INV-1001": "Örn: INV-1001",
        "قم بالبحث لإضافة منتجات": "Ürün eklemek için ara",
        "ملخص الدفع": "Ödeme Özeti",
        "المجموع الفرعي:": "Ara Toplam:",
        "خصم إضافي": "Ek İndirim",
        "الصافي النهائي:": "Net Toplam:",
        "المدفوعات": "Ödemeler",
        "💰 نقدي": "💰 Nakit",
        "💳 بطاقة": "💳 Kart",
        "🏦 تحويل": "🏦 Havale",
        "المتبقي:": "Kalan:",
        "رصيد (لك):": "Bakiye (Alacak):",
        "متبقي (عليك):": "Bakiye (Borç):",
        "خالص (تم الدفع بالكامل)": "Ödendi (Kapandı)",
        "حفظ الفاتورة": "Faturayı Kaydet",
        "إضافة مورد جديد": "Tedarikçi Ekle",
        "الاسم *": "Ad *",
        "الشركة": "Şirket",
        "حفظ وإضافة": "Kaydet ve Ekle",
        "إضافة منتج سريع": "Hızlı Ürün Ekle",
        "قريباً...": "Yakında...",
        "وحدات إضافية": "Ek Birimler",
        "أصغر وحدة": "En Küçük Birim",
        "خالص": "Ödendi",
        "أحجام/وحدات تقديم": "Boyutlar/Servis Birimleri"
    },
    "de": {
        "إضافة منتج جديد": "Neues Produkt hinzufügen",
        "منتج فعال": "Aktives Produkt",
        "البيانات الأساسية": "Basisinformationen",
        "اسم المنتج (عربي)": "Produktname (Arabisch)",
        "مثال: شيبس ليز ملح": "Bsp: Lays Chips gesalzen",
        "بحث في جوجل صور": "Google Bilder durchsuchen",
        "اسم المنتج (إنجليزي)": "Produktname (Englisch)",
        "التصنيف": "Kategorie",
        "-- اختر تصنيف --": "-- Kategorie auswählen --",
        "الوصف": "Beschreibung",
        "الوحدة الأساسية (أصغر وحدة)": "Basiseinheit (kleinste Einheit)",
        "صورة الوحدة": "Einheitsbild",
        "اسم الوحدة": "Einheitsname",
        "قطعة": "Stück",
        "كيلو": "Kilo",
        "علبة": "Karton",
        "مخصص..": "Benutzerdefiniert..",
        "سعر الشراء (للعبوة)": "Einkaufspreis (pro Packung)",
        "عدد القطع بالعبوة": "Stück pro Packung",
        "باركود الوحدة": "Barcode der Einheit",
        "تلقائي إذا فارغ": "Automatisch bei Leerstand",
        "شراء": "Kauf",
        "بيع": "Verkauf",
        "سعر البيع": "Verkaufspreis",
        "التكلفة (للقطعة)": "Kosten (pro Stück)",
        "الربح %": "Gewinn %",
        "الضريبة المضافة": "MwSt.",
        "السعر مع الضريبة": "Preis inkl. MwSt.",
        "الوحدات الإضافية (كرتون، درزن...)": "Zusätzliche Einheiten (Karton, Dutzend...)",
        "إضافة وحدة": "Einheit hinzufügen",
        "حد التنبيه للمخزون": "Bestandswarnlimit",
        "حفظ المنتج": "Produkt speichern",
        "كرتون": "Karton",
        "درزن": "Dutzend",
        "شريط": "Streifen",
        "اكتب الاسم": "Name eingeben",
        "التحويل": "Konvertierung",
        "الباركود": "Barcode",
        "التكلفة (آلي)": "Kosten (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Bitte Produktnamen zuerst auf Arabisch eingeben",
        "نبهني قبل X يوم": "X Tage vorher warnen",
        "تعديل المنتج:": "Produkt bearbeiten:",
        "فاتورة شراء جديدة": "Neue Einkaufsrechnung",
        "العودة": "Zurück",
        "المورد": "Lieferant",
        "مورد جديد": "Neuer Lieferant",
        "ابحث عن مورد...": "Lieferanten suchen...",
        "تاريخ وتوقيت الفاتورة": "Rechnungsdatum & Zeit",
        "رقم الفاتورة (للمورد)": "Rechnungsnummer (Lieferant)",
        "مثال: INV-1001": "Bsp: INV-1001",
        "قم بالبحث لإضافة منتجات": "Suchen, um Produkte hinzuzufügen",
        "ملخص الدفع": "Zahlungsübersicht",
        "المجموع الفرعي:": "Zwischensumme:",
        "خصم إضافي": "Zusätzlicher Rabatt",
        "الصافي النهائي:": "Endnetto:",
        "المدفوعات": "Zahlungen",
        "💰 نقدي": "💰 Bar",
        "💳 بطاقة": "💳 Karte",
        "🏦 تحويل": "🏦 Überweisung",
        "المتبقي:": "Verbleibend:",
        "رصيد (لك):": "Guthaben (für Sie):",
        "متبقي (عليك):": "Saldo (fällig):",
        "خالص (تم الدفع بالكامل)": "Bezahlt (Erledigt)",
        "حفظ الفاتورة": "Rechnung speichern",
        "إضافة مورد جديد": "Lieferant hinzufügen",
        "الشركة": "Firma",
        "حفظ وإضافة": "Speichern & Hinzufügen",
        "إضافة منتج سريع": "Produktschnellzugriff",
        "قريباً...": "Demnächst...",
        "أصغر وحدة": "Kleinste Einheit",
        "خالص": "Erledigt",
        "أحجام/وحدات تقديم": "Größen/Serviereinheiten"
    },
    "ru": {
        "إضافة منتج جديد": "Добавить новый продукт",
        "منتج فعال": "Активный продукт",
        "البيانات الأساسية": "Основная информация",
        "اسم المنتج (عربي)": "Название (арабский)",
        "مثال: شيبس ليز ملح": "Пример: Чипсы Lay's соль",
        "بحث في جوجل صور": "Искать в Google Картинках",
        "اسم المنتج (إنجليزي)": "Название (английский)",
        "التصنيف": "Категория",
        "-- اختر تصنيف --": "-- Выберите категорию --",
        "الوصف": "Описание",
        "الوحدة الأساسية (أصغر وحدة)": "Базовая единица (наименьшая)",
        "صورة الوحدة": "Изображение единицы",
        "اسم الوحدة": "Название единицы",
        "قطعة": "Шт.",
        "كيلو": "Кг",
        "علبة": "Коробка",
        "مخصص..": "Свой вариант..",
        "سعر الشراء (للعبوة)": "Цена закупки (за упак.)",
        "عدد القطع بالعبوة": "Штук в упаковке",
        "باركود الوحدة": "Штрих-код единицы",
        "تلقائي إذا فارغ": "Авто, если пусто",
        "شراء": "Закупка",
        "بيع": "Продажа",
        "سعر البيع": "Цена продажи",
        "التكلفة (للقطعة)": "Себестоимость (за шт.)",
        "الربح %": "Прибыль %",
        "الضريبة المضافة": "НДС",
        "السعر مع الضريبة": "Цена с НДС",
        "الوحدات الإضافية (كرتون، درزن...)": "Доп. единицы (Коробка, Дюжина...)",
        "إضافة وحدة": "Добавить единицу",
        "حد التنبيه للمخزون": "Лимит оповещения",
        "حفظ المنتج": "Сохранить продукт",
        "كرتون": "Коробка",
        "درزن": "Дюжина",
        "شريط": "Полоска",
        "اكتب الاسم": "Введите название",
        "التحويل": "Конверсия",
        "الباركود": "Штрих-код",
        "التكلفة (آلي)": "Себестоимость (Авто)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Пожалуйста, сначала введите название на арабском",
        "نبهني قبل X يوم": "Оповещение за X дней",
        "تعديل المنتج:": "Редактировать продукт:",
        "فاتورة شراء جديدة": "Новая накладная",
        "العودة": "Назад",
        "المورد": "Поставщик",
        "مورد جديد": "Новый поставщик",
        "ابحث عن مورد...": "Поиск поставщика...",
        "تاريخ وتوقيت الفاتورة": "Дата и время",
        "رقم الفاتورة (للمورد)": "Номер накладной (поставщик)",
        "مثال: INV-1001": "Пример: INV-1001",
        "قم بالبحث لإضافة منتجات": "Поиск для добавления продуктов",
        "ملخص الدفع": "Итого по оплате",
        "المجموع الفرعي:": "Подытог:",
        "خصم إضافي": "Доп. скидка",
        "الصافي النهائي:": "Итого к оплате:",
        "المدفوعات": "Платежи",
        "💰 نقدي": "💰 Наличные",
        "💳 بطاقة": "💳 Карта",
        "🏦 تحويل": "🏦 Перевод",
        "المتبقي:": "Остаток:",
        "رصيد (لك):": "Кредит (вам):",
        "متبقي (عليك):": "Баланс (долг):",
        "خالص (تم الدفع بالكامل)": "Оплачено",
        "حفظ الفاتورة": "Сохранить накладную",
        "إضافة مورد جديد": "Добавить поставщика",
        "الاسم *": "Имя *",
        "الشركة": "Компания",
        "حفظ وإضافة": "Сохранить и добавить",
        "إضافة منتج سريع": "Быстрое добавление",
        "قريباً...": "Скоро...",
        "أصغر وحدة": "Наим. единица",
        "خالص": "Оплачено",
        "أحجام/وحدات تقديم": "Размер порции"
    },
    "es": {
        "إضافة منتج جديد": "Añadir nuevo producto",
        "منتج فعال": "Producto activo",
        "البيانات الأساسية": "Información básica",
        "اسم المنتج (عربي)": "Nombre del producto (árabe)",
        "مثال: شيبس ليز ملح": "Ej: Papas Lays Sal",
        "بحث في جوجل صور": "Buscar en Google Imágenes",
        "اسم المنتج (إنجليزي)": "Nombre del producto (inglés)",
        "التصنيف": "Categoría",
        "-- اختر تصنيف --": "-- Seleccionar categoría --",
        "الوصف": "Descripción",
        "الوحدة الأساسية (أصغر وحدة)": "Unidad base (unidad más pequeña)",
        "صورة الوحدة": "Imagen de la unidad",
        "اسم الوحدة": "Nombre de la unidad",
        "قطعة": "Pieza",
        "كيلو": "Kilo",
        "علبة": "Caja",
        "مخصص..": "Personalizado..",
        "سعر الشراء (للعبوة)": "Precio de compra (por envase)",
        "عدد القطع بالعبوة": "Piezas por envase",
        "باركود الوحدة": "Código de barras",
        "تلقائي إذا فارغ": "Auto si está vacío",
        "شراء": "Compra",
        "بيع": "Venta",
        "سعر البيع": "Precio de venta",
        "التكلفة (للقطعة)": "Costo (por pieza)",
        "الربح %": "Ganancia %",
        "الضريبة المضافة": "IVA",
        "السعر مع الضريبة": "Precio con IVA",
        "الوحدات الإضافية (كرتون، درزن...)": "Unidades adicionales (Caja, Docena...)",
        "إضافة وحدة": "Añadir unidad",
        "حد التنبيه للمخزون": "Límite de alerta de stock",
        "حفظ المنتج": "Guardar producto",
        "كرتون": "Caja",
        "درزن": "Docena",
        "شريط": "Tira",
        "اكتب الاسم": "Escriba el nombre",
        "التحويل": "Conversión",
        "الباركود": "Código de barras",
        "التكلفة (آلي)": "Costo (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Escriba primero el nombre en árabe",
        "نبهني قبل X يوم": "Avisar X días antes",
        "تعديل المنتج:": "Editar producto:",
        "فاتورة شراء جديدة": "Nueva factura de compra",
        "العودة": "Volver",
        "المورد": "Proveedor",
        "مورد جديد": "Nuevo proveedor",
        "ابحث عن مورد...": "Buscar proveedor...",
        "تاريخ وتوقيت الفاتورة": "Fecha y hora de la factura",
        "رقم الفاتورة (للمورد)": "Número de factura (Proveedor)",
        "مثال: INV-1001": "Ej: INV-1001",
        "قم بالبحث لإضافة منتجات": "Buscar para añadir productos",
        "ملخص الدفع": "Resumen de pago",
        "المجموع الفرعي:": "Subtotal:",
        "خصم إضافي": "Descuento adicional",
        "الصافي النهائي:": "Neto final:",
        "المدفوعات": "Pagos",
        "💰 نقدي": "💰 Efectivo",
        "💳 بطاقة": "💳 Tarjeta",
        "🏦 تحويل": "🏦 Transferencia",
        "المتبقي:": "Restante:",
        "رصيد (لك):": "Crédito (para usted):",
        "متبقي (عليك):": "Saldo (pendiente):",
        "خالص (تم الدفع بالكامل)": "Pagado (Liquidado)",
        "حفظ الفاتورة": "Guardar factura",
        "إضافة مورد جديد": "Añadir proveedor",
        "الاسم *": "Nombre *",
        "الشركة": "Empresa",
        "حفظ وإضافة": "Guardar y añadir",
        "إضافة منتج سريع": "Añadir rápido",
        "قريباً...": "Pronto...",
        "أصغر وحدة": "Unidad mín.",
        "خالص": "Pagado",
        "أحجام/وحدات تقديم": "Tamaños/Unidades de servicio"
    },
    "pt-BR": {
        "إضافة منتج جديد": "Adicionar Novo Produto",
        "منتج فعال": "Produto Ativo",
        "البيانات الأساسية": "Informações Básicas",
        "اسم المنتج (عربي)": "Nome do Produto (Árabe)",
        "مثال: شيبس ليز ملح": "Ex: Batatas Lays Sal",
        "بحث في جوجل صور": "Pesquisar Google Imagens",
        "اسم المنتج (إنجليزي)": "Nome do Produto (Inglês)",
        "التصنيف": "Categoria",
        "-- اختر تصنيف --": "-- Selecionar Categoria --",
        "الوصف": "Descrição",
        "الوحدة الأساسية (أصغر وحدة)": "Unidade Base (Menor Unidade)",
        "صورة الوحدة": "Imagem da Unidade",
        "اسم الوحدة": "Nome da Unidade",
        "قطعة": "Peça",
        "كيلو": "Quilo",
        "علبة": "Caixa",
        "مخصص..": "Personalizado..",
        "سعر الشراء (للعبوة)": "Preço de Compra (por pacote)",
        "عدد القطع بالعبوة": "Peças por Pacote",
        "باركود الوحدة": "Código de Barras",
        "تلقائي إذا فارغ": "Auto se vazio",
        "شراء": "Compra",
        "بيع": "Venda",
        "سعر البيع": "Preço de Venda",
        "التكلفة (للقطعة)": "Custo (por peça)",
        "الربح %": "Lucro %",
        "الضريبة المضافة": "Imposto (ICMS)",
        "السعر مع الضريبة": "Preço com Imposto",
        "الوحدات الإضافية (كرتون، درزن...)": "Unidades Adicionais (Caixa, Dúzia...)",
        "إضافة وحدة": "Adicionar Unidade",
        "حد التنبيه للمخزون": "Limite de Alerta de Estoque",
        "حفظ المنتج": "Salvar Produto",
        "كرتون": "Caixa",
        "درزن": "Dúzia",
        "شريط": "Fita",
        "اكتب الاسم": "Digite o nome",
        "التحويل": "Conversão",
        "الباركود": "Código de Barras",
        "التكلفة (آلي)": "Custo (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Escreva o nome em árabe primeiro",
        "نبهني قبل X يوم": "Alertar X dias antes",
        "تعديل المنتج:": "Editar Produto:",
        "فاتورة شراء جديدة": "Nova Fatura de Compra",
        "العودة": "Voltar",
        "المورد": "Fornecedor",
        "مورد جديد": "Novo Fornecedor",
        "ابحث عن مورد...": "Pesquisar fornecedor...",
        "تاريخ وتوقيت الفاتورة": "Data e Hora da Fatura",
        "رقم الفاتورة (للمورد)": "Número da Fatura (Fornecedor)",
        "مثال: INV-1001": "Ex: INV-1001",
        "قم بالبحث لإضافة منتجات": "Pesquise para adicionar produtos",
        "ملخص الدفع": "Resumo do Pagamento",
        "المجموع الفرعي:": "Subtotal:",
        "خصم إضافي": "Desconto Adicional",
        "الصافي النهائي:": "Total Líquido:",
        "المدفوعات": "Pagamentos",
        "💰 نقدي": "💰 Dinheiro",
        "💳 بطاقة": "💳 Cartão",
        "🏦 تحويل": "🏦 Transferência",
        "المتبقي:": "Restante:",
        "رصيد (لك):": "Crédito (seu):",
        "متبقي (عليك):": "Saldo (devedor):",
        "خالص (تم الدفع بالكامل)": "Pago (Liquidado)",
        "حفظ الفاتورة": "Salvar Fatura",
        "إضافة مورد جديد": "Adicionar Fornecedor",
        "الاسم *": "Nome *",
        "الشركة": "Empresa",
        "حفظ وإضافة": "Salvar e Adicionar",
        "إضافة منتج سريع": "Adição Rápida",
        "قريباً...": "Em breve...",
        "أصغر وحدة": "Menor Unidade",
        "خالص": "Pago",
        "أحجام/وحدات تقديم": "Tamanhos/Unidades de Serviço"
    },
    "hr": {
        "إضافة منتج جديد": "Dodaj novi proizvod",
        "منتج فعال": "Aktivni proizvod",
        "البيانات الأساسية": "Osnovne informacije",
        "اسم المنتج (عربي)": "Naziv proizvoda (arapski)",
        "مثال: شيبس ليز ملح": "Npr: Lays čips slani",
        "بحث في جوجل صور": "Traži Google slike",
        "اسم المنتج (إنجليزي)": "Naziv proizvoda (engleski)",
        "التصنيف": "Kategorija",
        "-- اختر تصنيف --": "-- Odaberi kategoriju --",
        "الوصف": "Opis",
        "الوحدة الأساسية (أصغر وحدة)": "Osnovna jedinica (najmanja)",
        "صورة الوحدة": "Slika jedinice",
        "اسم الوحدة": "Naziv jedinice",
        "قطعة": "Komad",
        "كيلو": "Kilo",
        "علبة": "Kutija",
        "مخصص..": "Prilagođeno..",
        "سعر الشراء (للعبوة)": "Nabavna cijena (po pakiranju)",
        "عدد القطع بالعبوة": "Komada u pakiranju",
        "باركود الوحدة": "Barkod jedinice",
        "تلقائي إذا فارغ": "Automatski ako je prazno",
        "شراء": "Nabava",
        "بيع": "Prodaja",
        "سعر البيع": "Prodajna cijena",
        "التكلفة (للقطعة)": "Trošak (po komadu)",
        "الربح %": "Dobit %",
        "الضريبة المضافة": "PDV",
        "السعر مع الضريبة": "Cijena s PDV-om",
        "الوحدات الإضافية (كرتون، درزن...)": "Dodatne jedinice (Karton, Tucet...)",
        "إضافة وحدة": "Dodaj jedinicu",
        "حد التنبيه للمخزون": "Granica upozorenja zaliha",
        "حفظ المنتج": "Spremi proizvod",
        "كرتون": "Karton",
        "درزن": "Tucet",
        "شريط": "Traka",
        "اكتب الاسم": "Upiši naziv",
        "التحويل": "Konverzija",
        "الباركود": "Barkod",
        "التكلفة (آلي)": "Trošak (Auto)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "Prvo upišite naziv na arapskom",
        "نبهني قبل X يوم": "Upozori me X dana prije",
        "تعديل المنتج:": "Uredi proizvod:",
        "فاتورة شراء جديدة": "Novi račun nabave",
        "العودة": "Natrag",
        "المورد": "Dobavljač",
        "مورد جديد": "Novi dobavljač",
        "ابحث عن مورد...": "Traži dobavljača...",
        "تاريخ وتوقيت الفاتورة": "Datum i vrijeme računa",
        "رقم الفاتورة (للمورد)": "Broj računa (dobavljač)",
        "مثال: INV-1001": "Npr: INV-1001",
        "قم بالبحث لإضافة منتجات": "Traži za dodavanje proizvoda",
        "ملخص الدفع": "Sažetak plaćanja",
        "المجموع الفرعي:": "Međuzbroj:",
        "خصم إضافي": "Dodatni popust",
        "الصافي النهائي:": "Konačni neto:",
        "المدفوعات": "Plaćanja",
        "💰 نقدي": "💰 Gotovina",
        "💳 بطاقة": "💳 Kartica",
        "🏦 تحويل": "🏦 Transfer",
        "المتبقي:": "Preostalo:",
        "رصيد (لك):": "Kredit (vaš):",
        "متبقي (عليك):": "Saldo (dug):",
        "خالص (تم الدفع بالكامل)": "Plaćeno (Izmireno)",
        "حفظ الفاتورة": "Spremi račun",
        "إضافة مورد جديد": "Dodaj dobavljača",
        "الاسم *": "Ime *",
        "الشركة": "Tvrtka",
        "حفظ وإضافة": "Spremi i dodaj",
        "إضافة منتج سريع": "Brzo dodavanje",
        "قريباً...": "Uskoro...",
        "أصغر وحدة": "Najmanja jed.",
        "خالص": "Plaćeno",
        "أحجام/وحدات تقديم": "Veličine/Jedinice posluživanja"
    },
    "ja": {
        "إضافة منتج جديد": "新しい製品を追加",
        "منتج فعال": "有効な製品",
        "البيانات الأساسية": "基本情報",
        "اسم المنتج (عربي)": "製品名 (アラビア語)",
        "مثال: شيبس ليز ملح": "例：レイズ ポテトチップス 塩",
        "بحث في جوجل صور": "Google画像を検索",
        "اسم المنتج (إنجليزي)": "製品名 (英語)",
        "التصنيف": "カテゴリー",
        "-- اختر تصنيف --": "-- カテゴリーを選択 --",
        "الوصف": "説明",
        "الوحدة الأساسية (أصغر وحدة)": "基本単位 (最小単位)",
        "صورة الوحدة": "単位画像",
        "اسم الوحدة": "単位名",
        "قطعة": "個",
        "كيلو": "キロ",
        "علبة": "箱",
        "مخصص..": "カスタム..",
        "سعر الشراء (للعبوة)": "購入価格 (パックあたり)",
        "عدد القطع بالعبوة": "パックあたりの個数",
        "باركود الوحدة": "バーコード",
        "تلقائي إذا فارغ": "空の場合は自動生成",
        "شراء": "仕入れ",
        "بيع": "販売",
        "سعر البيع": "販売価格",
        "التكلفة (للقطعة)": "コスト (個別)",
        "الربح %": "利益 %",
        "الضريبة المضافة": "消費税",
        "السعر مع الضريبة": "税込価格",
        "الوحدات الإضافية (كرتون، درزن...)": "追加単位 (ケース、ダース...)",
        "إضافة وحدة": "単位を追加",
        "حد التنبيه للمخزون": "在庫アラート制限",
        "حفظ المنتج": "製品を保存",
        "كرتون": "ケース",
        "درزن": "ダース",
        "شريط": "ストリップ",
        "اكتب الاسم": "名前を入力",
        "التحويل": "変換",
        "الباركود": "バーコード",
        "التكلفة (آلي)": "コスト (自動)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "まずアラビア語で名前を入力してください",
        "نبهني قبل X يوم": "X日前に通知",
        "تعديل المنتج:": "製品を編集:",
        "فاتورة شراء جديدة": "新しい仕入れ請求書",
        "العودة": "戻る",
        "المورد": "仕入先",
        "مورد جديد": "新しい仕入先",
        "ابحث عن مورد...": "仕入先を検索...",
        "تاريخ وتوقيت الفاتورة": "請求書の日時",
        "رقم الفاتورة (للمورد)": "請求書番号 (仕入先)",
        "مثال: INV-1001": "例: INV-1001",
        "قم بالبحث لإضافة منتجات": "検索して製品を追加",
        "ملخص الدفع": "支払い概要",
        "المجموع الفرعي:": "小計:",
        "خصم إضافي": "追加割引",
        "الصافي النهائي:": "最終純額:",
        "المدفوعات": "支払い",
        "💰 نقدي": "💰 現金",
        "💳 بطاقة": "💳 カード",
        "🏦 تحويل": "🏦 銀行振込",
        "المتبقي:": "残り:",
        "رصيد (لك):": "クレジット (あなた用):",
        "متبقي (عليك):": "残高 (未払い):",
        "خالص (تم الدفع بالكامل)": "支払い済み (完了)",
        "حفظ الفاتورة": "請求書を保存",
        "إضافة مورد جديد": "仕入先を追加",
        "الاسم *": "名前 *",
        "الشركة": "会社",
        "حفظ وإضافة": "保存して追加",
        "إضافة منتج سريع": "製品をクイック追加",
        "قريباً...": "近日公開...",
        "أصغر وحدة": "最小単位",
        "خالص": "完了",
        "أحجام/وحدات تقديم": "サイズ/提供単位"
    },
    "zh": {
        "إضافة منتج جديد": "添加新产品",
        "منتج فعال": "有效产品",
        "البيانات الأساسية": "基本信息",
        "اسم المنتج (عربي)": "产品名称 (阿拉伯语)",
        "مثال: شيبس ليز ملح": "例如：乐事薯片盐味",
        "بحث في جوجل صور": "谷歌图片搜索",
        "اسم المنتج (إنجليزي)": "产品名称 (英语)",
        "التصنيف": "类别",
        "-- اختر تصنيف --": "-- 选择类别 --",
        "الوصف": "描述",
        "الوحدة الأساسية (أصغر وحدة)": "基本单位 (最小单位)",
        "صورة الوحدة": "单位图片",
        "اسم الوحدة": "单位名称",
        "قطعة": "件",
        "كيلو": "公斤",
        "علبة": "盒",
        "مخصص..": "自定义..",
        "سعر الشراء (للعبوة)": "购买价格 (每包)",
        "عدد القطع بالعبوة": "每包件数",
        "باركود الوحدة": "单位条形码",
        "تلقائي إذا فارغ": "为空时自动生成",
        "شراء": "采购",
        "بيع": "销售",
        "سعر البيع": "销售价格",
        "التكلفة (للقطعة)": "成本 (每件)",
        "الربح %": "利润 %",
        "الضريبة المضافة": "增值税",
        "السعر مع الضريبة": "含税价格",
        "الوحدات الإضافية (كرتون، درزن...)": "附加单位 (箱, 打...)",
        "إضافة وحدة": "添加单位",
        "حد التنبيه للمخزون": "库存警报限制",
        "حفظ المنتج": "保存产品",
        "كرتون": "箱",
        "درزن": "打",
        "شريط": "条",
        "اكتب الاسم": "输入名称",
        "التحويل": "转换",
        "الباركود": "条形码",
        "التكلفة (آلي)": "成本 (自动)",
        "الرجاء كتابة اسم المنتج بالعربي أولاً": "请先输入阿拉伯语名称",
        "نبهني قبل X يوم": "提前 X 天通知",
        "تعديل المنتج:": "编辑产品:",
        "فاتورة شراء جديدة": "新采购发票",
        "العودة": "返回",
        "المورد": "供应商",
        "مورد جديد": "新供应商",
        "ابحث عن مورد...": "搜索供应商...",
        "تاريخ وتوقيت الفاتورة": "发票日期和时间",
        "رقم الفاتورة (للمورد)": "发票号码 (供应商)",
        "مثال: INV-1001": "例如: INV-1001",
        "قم بالبحث لإضافة منتجات": "搜索以添加产品",
        "ملخص الدفع": "付款摘要",
        "المجموع الفرعي:": "小计:",
        "خصم إضافي": "额外折扣",
        "الصافي النهائي:": "最终净额:",
        "المدفوعات": "付款",
        "💰 نقدي": "💰 现金",
        "💳 بطاقة": "💳 银行卡",
        "🏦 تحويل": "🏦 银行转账",
        "المتبقي:": "剩余:",
        "رصيد (لك):": "余额 (您的):",
        "متبقي (عليك):": "余额 (欠款):",
        "خالص (تم الدفع بالكامل)": "已付清 (完成)",
        "حفظ الفاتورة": "保存发票",
        "إضافة مورد جديد": "添加供应商",
        "الاسم *": "姓名 *",
        "الشركة": "公司",
        "حفظ وإضافة": "保存并添加",
        "إضافة منتج سريع": "快速添加产品",
        "قريباً...": "即将推出...",
        "أصغر وحدة": "最小单位",
        "خالص": "完成",
        "أحجام/وحدات تقديم": "尺寸/供餐单位"
    }
}



lang_dir = r'c:\\xampp\\htdocs\\system\\resources\\lang'

for lang, mapping in translations.items():
    file_path = os.path.join(lang_dir, lang + ".json")
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
            except:
                data = {}
        
        updated = False
        for ar_key, trans_val in mapping.items():
            data[ar_key] = trans_val
            updated = True
            
        if updated:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)
            print(f"Updated {lang}.json with {len(mapping)} translations.")
