import json
import os

langs = {
    "ar": {
        "inventory_logs_title": "سجل تعديلات المخزون",
        "print_btn": "طباعة",
        "whatsapp_btn": "واتساب",
        "email_btn": "بريد إلكتروني",
        "search_product_barcode": "البحث (منتج / باركود)",
        "search_product_barcode_placeholder": "اسم المنتج أو الباركود...",
        "rows_count": "الصفوف",
        "product_name": "اسم المنتج",
        "barcode": "الباركود",
        "adjustment_date": "تاريخ التعديل",
        "action_type": "نوع العملية",
        "status_before": "الحالة قبل",
        "status_after": "الحالة بعد",
        "by_user": "بواسطة",
        "action_reason": "السبب",
        "deleted_product": "منتج محذوف",
        "manual_adjustment": "تعديل يدوي",
        "dispose_inventory": "إتلاف مخزون",
        "extend_expiry": "مدد الصلاحية",
        "no_matching_adjustment_records": "لا توجد سجلات تعديل مطابقة للفلاتر المختارة",
        "product_label": "المنتج",
        "date_label": "التاريخ",
        "action_label": "العملية",
        "before_label": "قبل",
        "after_label": "بعد",
        "dispose_label": "إتلاف",
        "extend_label": "تمديد",
        "report_generated_by_smart_store": "تم توليد التقرير بواسطة نظام إدارة المتاجر الذكي",
        "preparing_inventory_report": "جاري تجهيز تقرير المخزون...",
        "inventory_report_whatsapp_text": "*تقرير سجل تعديلات المخزون*\\nالمتجر: ",
        "report_date": "تاريخ التقرير: ",
        "attached_detailed_manual_adjustments_report": "مرفق لكم التقرير التفصيلي للتعديلات اليدوية.",
        "send_logs_pdf_attachment": "إرسال سجل التعديلات كمرفق PDF",
        "error_whatsapp_func_unavailable": "حدث خطأ: وظيفة إرسال الواتساب غير متوفرة",
        "failed_prepare_report_file": "فشل تجهيز ملف التقرير",
        "error_communicate_server": "حدث خطأ أثناء التواصل مع السيرفر",
        "preparing_send_request": "جاري تجهيز طلب الإرسال...",
        "error_email_func_unavailable": "حدث خطأ: وظيفة إرسال البريد غير متوفرة"
    },
    "en": {
        "inventory_logs_title": "Inventory Logs",
        "print_btn": "Print",
        "whatsapp_btn": "WhatsApp",
        "email_btn": "Email",
        "search_product_barcode": "Search (Product / Barcode)",
        "search_product_barcode_placeholder": "Product Name or Barcode...",
        "rows_count": "Rows",
        "product_name": "Product Name",
        "barcode": "Barcode",
        "adjustment_date": "Adjustment Date",
        "action_type": "Action Type",
        "status_before": "Status Before",
        "status_after": "Status After",
        "by_user": "By",
        "action_reason": "Reason",
        "deleted_product": "Deleted Product",
        "manual_adjustment": "Manual Adjustment",
        "dispose_inventory": "Dispose Inventory",
        "extend_expiry": "Extend Expiry",
        "no_matching_adjustment_records": "No adjustment records match the selected filters",
        "product_label": "Product",
        "date_label": "Date",
        "action_label": "Action",
        "before_label": "Before",
        "after_label": "After",
        "dispose_label": "Dispose",
        "extend_label": "Extend",
        "report_generated_by_smart_store": "Report generated by Smart Store Management System",
        "preparing_inventory_report": "Preparing Inventory Report...",
        "inventory_report_whatsapp_text": "*Inventory Adjustment Logs Report*\\nStore: ",
        "report_date": "Report Date: ",
        "attached_detailed_manual_adjustments_report": "Attached is the detailed report for manual adjustments.",
        "send_logs_pdf_attachment": "Send Adjustment Logs as PDF Attachment",
        "error_whatsapp_func_unavailable": "Error: WhatsApp sending function is unavailable",
        "failed_prepare_report_file": "Failed to prepare report file",
        "error_communicate_server": "Error communicating with the server",
        "preparing_send_request": "Preparing Send Request...",
        "error_email_func_unavailable": "Error: Email sending function is unavailable"
    },
    "es": {
        "inventory_logs_title": "Registros de Inventario", "print_btn": "Imprimir", "whatsapp_btn": "WhatsApp", "email_btn": "Correo electrónico", "search_product_barcode": "Buscar (Producto / Código de barras)", "search_product_barcode_placeholder": "Nombre del Producto o Código de barras...", "rows_count": "Filas", "product_name": "Nombre del Producto", "barcode": "Código de barras", "adjustment_date": "Fecha de Ajuste", "action_type": "Tipo de Acción", "status_before": "Estado Anterior", "status_after": "Estado Posterior", "by_user": "Por", "action_reason": "Razón", "deleted_product": "Producto Eliminado", "manual_adjustment": "Ajuste Manual", "dispose_inventory": "Desechar Inventario", "extend_expiry": "Extender Vencimiento", "no_matching_adjustment_records": "No hay registros de ajuste que coincidan con los filtros seleccionados", "product_label": "Producto", "date_label": "Fecha", "action_label": "Acción", "before_label": "Antes", "after_label": "Después", "dispose_label": "Desechar", "extend_label": "Extender", "report_generated_by_smart_store": "Informe generado por el Sistema de Gestión de Tiendas Inteligente", "preparing_inventory_report": "Preparando Informe de Inventario...", "inventory_report_whatsapp_text": "*Informe de Registros de Ajuste de Inventario*\\nTienda: ", "report_date": "Fecha del Informe: ", "attached_detailed_manual_adjustments_report": "Adjunto se encuentra el informe detallado de ajustes manuales.", "send_logs_pdf_attachment": "Enviar Registros de Ajuste como Archivo Adjunto en PDF", "error_whatsapp_func_unavailable": "Error: La función de envío por WhatsApp no está disponible", "failed_prepare_report_file": "Error al preparar el archivo del informe", "error_communicate_server": "Error al comunicarse con el servidor", "preparing_send_request": "Preparando Solicitud de Envío...", "error_email_func_unavailable": "Error: La función de envío por correo electrónico no está disponible"
    },
    "tr": {
        "inventory_logs_title": "Envanter Kayıtları", "print_btn": "Yazdır", "whatsapp_btn": "WhatsApp", "email_btn": "E-posta", "search_product_barcode": "Arama (Ürün / Barkod)", "search_product_barcode_placeholder": "Ürün Adı veya Barkod...", "rows_count": "Satırlar", "product_name": "Ürün Adı", "barcode": "Barkod", "adjustment_date": "Düzenleme Tarihi", "action_type": "İşlem Türü", "status_before": "Önceki Durum", "status_after": "Sonraki Durum", "by_user": "Tarafından", "action_reason": "Neden", "deleted_product": "Silinmiş Ürün", "manual_adjustment": "Manuel Düzenleme", "dispose_inventory": "Envanteri İmha Et", "extend_expiry": "Son Kullanma Tarihini Uzat", "no_matching_adjustment_records": "Seçili filtrelere uygun düzenleme kaydı bulunamadı", "product_label": "Ürün", "date_label": "Tarih", "action_label": "İşlem", "before_label": "Önce", "after_label": "Sonra", "dispose_label": "İmha", "extend_label": "Uzat", "report_generated_by_smart_store": "Akıllı Mağaza Yönetim Sistemi tarafından oluşturulan rapor", "preparing_inventory_report": "Envanter Raporu Hazırlanıyor...", "inventory_report_whatsapp_text": "*Envanter Düzenleme Kayıtları Raporu*\\nMağaza: ", "report_date": "Rapor Tarihi: ", "attached_detailed_manual_adjustments_report": "Ekte, manuel düzenlemelere ilişkin detaylı rapor bulunmaktadır.", "send_logs_pdf_attachment": "Düzenleme Kayıtlarını PDF Eki Olarak Gönder", "error_whatsapp_func_unavailable": "Hata: WhatsApp gönderme işlevi kullanılamıyor", "failed_prepare_report_file": "Rapor dosyası hazırlanamadı", "error_communicate_server": "Sunucu ile iletişim hatası", "preparing_send_request": "Gönderme İsteği Hazırlanıyor...", "error_email_func_unavailable": "Hata: E-posta gönderme işlevi kullanılamıyor"
    },
    "ru": {
        "inventory_logs_title": "Журналы инвентаризации", "print_btn": "Печать", "whatsapp_btn": "WhatsApp", "email_btn": "Email", "search_product_barcode": "Поиск (Товар / Штрих-код)", "search_product_barcode_placeholder": "Название товара или Штрих-код...", "rows_count": "Строки", "product_name": "Название товара", "barcode": "Штрих-код", "adjustment_date": "Дата корректировки", "action_type": "Тип действия", "status_before": "Статус до", "status_after": "Статус после", "by_user": "Кем", "action_reason": "Причина", "deleted_product": "Удаленный товар", "manual_adjustment": "Ручная корректировка", "dispose_inventory": "Утилизация запасов", "extend_expiry": "Продлить срок годности", "no_matching_adjustment_records": "Нет записей корректировок, соответствующих выбранным фильтрам", "product_label": "Товар", "date_label": "Дата", "action_label": "Действие", "before_label": "До", "after_label": "После", "dispose_label": "Утилизировать", "extend_label": "Продлить", "report_generated_by_smart_store": "Отчет сгенерирован умной системой управления магазином", "preparing_inventory_report": "Подготовка отчета об инвентаризации...", "inventory_report_whatsapp_text": "*Отчет о корректировках инвентаризации*\\nМагазин: ", "report_date": "Дата отчета: ", "attached_detailed_manual_adjustments_report": "В приложении подробный отчет о ручных корректировках.", "send_logs_pdf_attachment": "Отправить журналы корректировок как вложение PDF", "error_whatsapp_func_unavailable": "Ошибка: функция отправки WhatsApp недоступна", "failed_prepare_report_file": "Не удалось подготовить файл отчета", "error_communicate_server": "Ошибка связи с сервером", "preparing_send_request": "Подготовка запроса на отправку...", "error_email_func_unavailable": "Ошибка: функция отправки Email недоступна"
    },
    "de": {
        "inventory_logs_title": "Inventarprotokolle", "print_btn": "Drucken", "whatsapp_btn": "WhatsApp", "email_btn": "E-Mail", "search_product_barcode": "Suchen (Produkt / Barcode)", "search_product_barcode_placeholder": "Produktname oder Barcode...", "rows_count": "Zeilen", "product_name": "Produktname", "barcode": "Barcode", "adjustment_date": "Anpassungsdatum", "action_type": "Aktionstyp", "status_before": "Status davor", "status_after": "Status danach", "by_user": "Von", "action_reason": "Grund", "deleted_product": "Gelöschtes Produkt", "manual_adjustment": "Manuelle Anpassung", "dispose_inventory": "Inventar entsorgen", "extend_expiry": "Ablaufdatum verlängern", "no_matching_adjustment_records": "Keine Anpassungsprotokolle entsprechen den ausgewählten Filtern", "product_label": "Produkt", "date_label": "Datum", "action_label": "Aktion", "before_label": "Zuvor", "after_label": "Danach", "dispose_label": "Entsorgen", "extend_label": "Verlängern", "report_generated_by_smart_store": "Bericht erstellt von dem Smart Store Management System", "preparing_inventory_report": "Inventarbericht wird vorbereitet...", "inventory_report_whatsapp_text": "*Inventaranpassungsprotokolle Bericht*\\nGeschäft: ", "report_date": "Berichtsdatum: ", "attached_detailed_manual_adjustments_report": "Angehängt ist der detaillierte Bericht über manuelle Anpassungen.", "send_logs_pdf_attachment": "Anpassungsprotokolle als PDF-Anhang senden", "error_whatsapp_func_unavailable": "Fehler: WhatsApp-Sende-Funktion ist nicht verfügbar", "failed_prepare_report_file": "Fehler beim Vorbereiten der Berichtsdatei", "error_communicate_server": "Fehler bei der Kommunikation mit dem Server", "preparing_send_request": "Sendeanfrage wird vorbereitet...", "error_email_func_unavailable": "Fehler: E-Mail-Sende-Funktion ist nicht verfügbar"
    },
    "fr": {
        "inventory_logs_title": "Journaux d'inventaire", "print_btn": "Imprimer", "whatsapp_btn": "WhatsApp", "email_btn": "E-mail", "search_product_barcode": "Rechercher (Produit / Code-barres)", "search_product_barcode_placeholder": "Nom du Produit ou Code-barres...", "rows_count": "Lignes", "product_name": "Nom du Produit", "barcode": "Code-barres", "adjustment_date": "Date d'Ajustement", "action_type": "Type d'Action", "status_before": "Statut Avant", "status_after": "Statut Après", "by_user": "Par", "action_reason": "Raison", "deleted_product": "Produit Supprimé", "manual_adjustment": "Ajustement Manuel", "dispose_inventory": "Jeter l'Inventaire", "extend_expiry": "Prolonger l'Expiration", "no_matching_adjustment_records": "Aucun enregistrement d'ajustement ne correspond aux filtres sélectionnés", "product_label": "Produit", "date_label": "Date", "action_label": "Action", "before_label": "Avant", "after_label": "Après", "dispose_label": "Jeter", "extend_label": "Prolonger", "report_generated_by_smart_store": "Rapport généré par le Système de Gestion de Magasin Intelligent", "preparing_inventory_report": "Préparation du Rapport d'Inventaire...", "inventory_report_whatsapp_text": "*Rapport des Journaux d'Ajustement d'Inventaire*\\nMagasin: ", "report_date": "Date du Rapport: ", "attached_detailed_manual_adjustments_report": "Veuillez trouver ci-joint le rapport détaillé des ajustements manuels.", "send_logs_pdf_attachment": "Envoyer les Journaux d'Ajustement en Pièce Jointe PDF", "error_whatsapp_func_unavailable": "Erreur : La fonction d'envoi WhatsApp est indisponible", "failed_prepare_report_file": "Échec de la préparation du fichier de rapport", "error_communicate_server": "Erreur de communication avec le serveur", "preparing_send_request": "Préparation de la Demande d'Envoi...", "error_email_func_unavailable": "Erreur : La fonction d'envoi par e-mail est indisponible"
    },
    "ja": {
        "inventory_logs_title": "在庫調整ログ", "print_btn": "印刷", "whatsapp_btn": "WhatsApp", "email_btn": "メール", "search_product_barcode": "検索 (製品 / バーコード)", "search_product_barcode_placeholder": "製品名またはバーコード...", "rows_count": "行数", "product_name": "製品名", "barcode": "バーコード", "adjustment_date": "調整日", "action_type": "アクションタイプ", "status_before": "変更前のステータス", "status_after": "変更後のステータス", "by_user": "操作者", "action_reason": "理由", "deleted_product": "削除された製品", "manual_adjustment": "手動調整", "dispose_inventory": "在庫の廃棄", "extend_expiry": "有効期限の延長", "no_matching_adjustment_records": "選択されたフィルターに一致する調整ログはありません", "product_label": "製品", "date_label": "日付", "action_label": "操作", "before_label": "前", "after_label": "後", "dispose_label": "廃棄", "extend_label": "延長", "report_generated_by_smart_store": "スマート店舗管理システムによって生成されたレポート", "preparing_inventory_report": "在庫レポートを作成中...", "inventory_report_whatsapp_text": "*在庫調整ログレポート*\\n店舗: ", "report_date": "レポート日: ", "attached_detailed_manual_adjustments_report": "詳細な手動調整レポートが添付されています。", "send_logs_pdf_attachment": "調整ログをPDF添付ファイルとして送信", "error_whatsapp_func_unavailable": "エラー: WhatsApp送信機能は利用できません", "failed_prepare_report_file": "レポートファイルの準備に失敗しました", "error_communicate_server": "サーバーとの通信エラー", "preparing_send_request": "送信リクエストを準備中...", "error_email_func_unavailable": "エラー: メール送信機能は利用できません"
    },
    "zh": {
        "inventory_logs_title": "库存调整日志", "print_btn": "打印", "whatsapp_btn": "WhatsApp", "email_btn": "电子邮件", "search_product_barcode": "搜索（产品/条形码）", "search_product_barcode_placeholder": "产品名称或条形码...", "rows_count": "行数", "product_name": "产品名称", "barcode": "条形码", "adjustment_date": "调整日期", "action_type": "操作类型", "status_before": "调整前状态", "status_after": "调整后状态", "by_user": "操作人", "action_reason": "原因", "deleted_product": "已删除产品", "manual_adjustment": "手动调整", "dispose_inventory": "清理库存", "extend_expiry": "延长保质期", "no_matching_adjustment_records": "没有匹配所选过滤器的调整日志记录", "product_label": "产品", "date_label": "日期", "action_label": "操作", "before_label": "之前", "after_label": "之后", "dispose_label": "清理", "extend_label": "延长", "report_generated_by_smart_store": "由智能门店管理系统生成的报告", "preparing_inventory_report": "正在准备库存报告...", "inventory_report_whatsapp_text": "*库存调整日志报告*\\n门店: ", "report_date": "报告日期: ", "attached_detailed_manual_adjustments_report": "附上详细的手动调整报告。", "send_logs_pdf_attachment": "以PDF附件形式发送调整日志", "error_whatsapp_func_unavailable": "错误：无法使用WhatsApp发送功能", "failed_prepare_report_file": "准备报告文件失败", "error_communicate_server": "与服务器通信时出错", "preparing_send_request": "正在准备发送请求...", "error_email_func_unavailable": "错误：无法使用电子邮件发送功能"
    },
    "pt": {
        "inventory_logs_title": "Registos de Inventário", "print_btn": "Imprimir", "whatsapp_btn": "WhatsApp", "email_btn": "E-mail", "search_product_barcode": "Pesquisar (Produto / Código de Barras)", "search_product_barcode_placeholder": "Nome do Produto ou Código de Barras...", "rows_count": "Linhas", "product_name": "Nome do Produto", "barcode": "Código de Barras", "adjustment_date": "Data de Ajuste", "action_type": "Tipo de Ação", "status_before": "Status Anterior", "status_after": "Status Posterior", "by_user": "Por", "action_reason": "Motivo", "deleted_product": "Produto Excluído", "manual_adjustment": "Ajuste Manual", "dispose_inventory": "Descartar Inventário", "extend_expiry": "Estender Validade", "no_matching_adjustment_records": "Nenhum registo de ajuste corresponde aos filtros selecionados", "product_label": "Produto", "date_label": "Data", "action_label": "Ação", "before_label": "Antes", "after_label": "Depois", "dispose_label": "Descartar", "extend_label": "Estender", "report_generated_by_smart_store": "Relatório gerado pelo Sistema de Gestão de Lojas Inteligente", "preparing_inventory_report": "Preparando Relatório de Inventário...", "inventory_report_whatsapp_text": "*Relatório de Ajustes de Inventário*\\nLoja: ", "report_date": "Data do Relatório: ", "attached_detailed_manual_adjustments_report": "Em anexo encontra-se o relatório detalhado dos ajustes manuais.", "send_logs_pdf_attachment": "Enviar Registos de Ajuste como Anexo em PDF", "error_whatsapp_func_unavailable": "Erro: A função de envio do WhatsApp não está disponível", "failed_prepare_report_file": "Falha ao preparar o arquivo de relatório", "error_communicate_server": "Erro de comunicação com o servidor", "preparing_send_request": "A preparar Pedido de Envio...", "error_email_func_unavailable": "Erro: A função de envio de e-mail não está disponível"
    },
    "pt-BR": {
        "inventory_logs_title": "Relatórios de Inventário", "print_btn": "Imprimir", "whatsapp_btn": "WhatsApp", "email_btn": "E-mail", "search_product_barcode": "Pesquisar (Produto / Código de Barras)", "search_product_barcode_placeholder": "Nome do Produto ou Código de Barras...", "rows_count": "Linhas", "product_name": "Nome do Produto", "barcode": "Código de Barras", "adjustment_date": "Data de Ajuste", "action_type": "Tipo de Ação", "status_before": "Status Anterior", "status_after": "Status Posterior", "by_user": "Por", "action_reason": "Motivo", "deleted_product": "Produto Excluído", "manual_adjustment": "Ajuste Manual", "dispose_inventory": "Descartar Inventário", "extend_expiry": "Estender Validade", "no_matching_adjustment_records": "Nenhum registo de ajuste corresponde aos filtros selecionados", "product_label": "Produto", "date_label": "Data", "action_label": "Ação", "before_label": "Antes", "after_label": "Depois", "dispose_label": "Descartar", "extend_label": "Estender", "report_generated_by_smart_store": "Relatório gerado pelo Sistema de Gestão de Lojas Inteligente", "preparing_inventory_report": "Preparando Relatório de Inventário...", "inventory_report_whatsapp_text": "*Relatório de Ajustes de Inventário*\\nLoja: ", "report_date": "Data do Relatório: ", "attached_detailed_manual_adjustments_report": "Em anexo encontra-se o relatório detalhado dos ajustes manuais.", "send_logs_pdf_attachment": "Enviar Registos de Ajuste como Anexo em PDF", "error_whatsapp_func_unavailable": "Erro: A função de envio do WhatsApp não está disponível", "failed_prepare_report_file": "Falha ao preparar o arquivo de relatório", "error_communicate_server": "Erro de comunicação com o servidor", "preparing_send_request": "A preparar Pedido de Envio...", "error_email_func_unavailable": "Erro: A função de envio de e-mail não está disponível"
    },
    "hr": {
        "inventory_logs_title": "Dnevnici Inventure", "print_btn": "Ispis", "whatsapp_btn": "WhatsApp", "email_btn": "E-mail", "search_product_barcode": "Pretraživanja (Proizvod / Barkod)", "search_product_barcode_placeholder": "Naziv proizvoda ili barkod...", "rows_count": "Redovi", "product_name": "Naziv proizvoda", "barcode": "Barkod", "adjustment_date": "Datum Prilagodbe", "action_type": "Vrsta Radnje", "status_before": "Stanje Prije", "status_after": "Stanje Poslije", "by_user": "Autor", "action_reason": "Razlog", "deleted_product": "Izbrisani Proizvod", "manual_adjustment": "Ručna Prilagodba", "dispose_inventory": "Zbrinjavanje Inventara", "extend_expiry": "Produljenje Roka", "no_matching_adjustment_records": "Nijedan zapis prilagodbe ne odgovara odabranim filtrima", "product_label": "Proizvod", "date_label": "Datum", "action_label": "Radnja", "before_label": "Prije", "after_label": "Poslije", "dispose_label": "Zbrinj.", "extend_label": "Produlj.", "report_generated_by_smart_store": "Izvješće generirano pomoću sustava upravljanja trgovinom Smart", "preparing_inventory_report": "Priprema izvješća o inventuri...", "inventory_report_whatsapp_text": "*Izvješće Dnevnika Prilagodbi Inventure*\\nTrgovina: ", "report_date": "Datum Izvješća: ", "attached_detailed_manual_adjustments_report": "U privitku je detaljno izvješće za ručne prilagodbe.", "send_logs_pdf_attachment": "Pošaljite dnevnike prilagodbe kao PDF prilog", "error_whatsapp_func_unavailable": "Graška: funkcija slanja WhatsApp poruka nije dostupna", "failed_prepare_report_file": "Neuspješna priprema datoteka s izvješćem", "error_communicate_server": "Pogreška prilikom komunikacije sa serverom", "preparing_send_request": "Priprema zahtjeva za slanje...", "error_email_func_unavailable": "Graška: funkcija slanja e-pošte nije dostupna"
    }
}

# The translations script looks okay, updating...
for lang, mapping in langs.items():
    filepath = f"resources/lang/{lang}.json"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for k, v in mapping.items():
            if k not in data or lang in ['ru', 'ja', 'zh', 'es', 'pt', 'pt-BR', 'hr', 'fr', 'de', 'tr']:
                data[k] = v
            # also for ar and en override to be safe
            elif lang in ['ar', 'en']:
                data[k] = v
            
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        print(f"Updated {filepath} for inventory logs")

print("Finished syncing inventory logs translation terms.")
