import json
import os

def translate_en_json(file_path):
    mapping = {
        "بحث عن عميل...": "Search for customer...",
        "تسجيل مسحوبات": "Record Withdrawals",
        "حفظ وطباعة (F9)": "Save & Print (F9)",
        "المنتج غير موجود": "Product not found",
        "مخزون:": "Stock:",
        "تمت الإضافة": "Added",
        "تم تعديل المخزون وتغيير الوحدة بنجاح": "Stock updated and unit changed successfully",
        "هذه الوحدة لا تقبل الكسور": "This unit does not accept fractions",
        "الكمية غير صحيحة": "Invalid quantity",
        "مسح الفاتورة؟": "Clear invoice?",
        "المتبقي:": "Remaining:",
        "المتبقي (عليه):": "Remaining (Due):",
        "رصيد إضافي (له):": "Extra Balance (Credit):",
        "تم تقريب المبلغ:": "Amount Rounded:",
        "💵 نقدي": "💵 Cash",
        "💳 شبكة / كرت": "💳 Card / POS",
        "🏦 تحويل بنكي": "🏦 Bank Transfer",
        "💳 PayPal / Cards": "💳 PayPal / Cards",
        "تم الدفع عبر PayPal بنجاح!": "PayPal payment successful!",
        "فشل تأكيد الدفع": "Payment confirmation failed",
        "حدث خطأ أثناء الدفع عبر PayPal": "Error occurred during PayPal payment",
        "الصندوق مغلق": "Cashier box is closed",
        "لا يمكن إتمام عملية البيع قبل فتح الصندوق (الوردية).": "Cannot complete sale before opening the shift.",
        "فتح الصندوق الآن": "Open box now",
        "السلة فارغة": "Cart is empty",
        "جاري الحفظ...": "Saving...",
        "تم الحفظ بنجاح": "Saved successfully",
        "كيف ترغب في مشاركة الفاتورة مع العميل؟": "How would you like to share the invoice with the customer?",
        "واتساب": "WhatsApp",
        "إيميل": "Email",
        "إغلاق": "Close",
        "إرسال فاتورة مبيعات - رقم #": "Send sales invoice - No. #",
        "تم تسجيل المسحوبات": "Withdrawals recorded",
        "تمت العملية بنجاح": "Process completed successfully",
        "تنبيه": "Alert",
        "تجاوز حد الدين": "Credit limit exceeded",
        "الحد الحالي:": "Current limit:",
        "هل تريد رفع الحد؟": "Do you want to raise the limit?",
        "نعم": "Yes",
        "إلغاء": "Cancel",
        "نقص مخزون": "Stock Shortage",
        "تعديل المخزون": "Adjust Stock",
        "خطأ": "Error",
        "حدث خطأ غير معروف": "Unknown error occurred",
        "مطلوب عميل": "Customer required",
        "لا يمكن تسجيل دين لعميل عام": "Cannot record debt for general customer",
        "سيصبح إجمالي الدين:": "Total debt will be:",
        "سيصبح رصيده:": "Balance will be:",
        "تأكيد تسجيل الدين": "Confirm recording debt",
        "قيمة الدين:": "Debt value:",
        "مبلغ زائد": "Overpaid amount",
        "المبلغ الزائد:": "Extra amount:",
        "✅ تم إرجاع الكاش": "✅ Cash returned",
        "مبلغ مدفوع زائد": "Excessive amount paid",
        "كيف تريد التعامل مع الباقي؟": "How do you want to handle the remaining?",
        "💰 إرجاع كاش": "💰 Refund Cash",
        "📥 إضافة لرصيد العميل": "📥 Add to customer balance",
        "الكمية غير كافية!": "Insufficient quantity!",
        "المنتج:": "Product:",
        "المخزون الحالي:": "Current stock:",
        "الكمية الجديدة:": "New quantity:",
        "حفظ": "Save",
        "خطأ:": "Error:",
        "تم!": "Done!",
        "تم تحديث المخزون.": "Stock updated.",
        "الكل": "All",
        "مدفوعة": "Paid",
        "جزئي": "Partial",
        "غير مدفوعة": "Unpaid",
        "عرض المرتجعات": "View Returns",
        "لا توجد بيانات": "No data available",
        "خطأ في الاتصال (Recent Sales)": "Connection Error (Recent Sales)",
        "إرجاع صنف": "Return Item",
        "الكمية المسترجعة (الحد الأقصى:": "Returned Qty (Max:",
        "السبب (اختياري)": "Reason (Optional)",
        "مثلاً: صنف تالف...": "E.g., Damaged item...",
        "تأكيد الإرجاع": "Confirm Return",
        "الرجاء إدخال كمية صحيحة": "Please enter a valid quantity",
        "الكمية لا يمكن أن تتجاوز": "Quantity cannot exceed",
        "تم الإرجاع بنجاح": "Returned successfully",
        "حدث خطأ": "An error occurred",
        "تحديث صلاحية": "Update Expiry",
        "سبب التحديث:": "Update Reason:",
        "مثلاً: خطأ في الادخال، تمديد من المورد...": "E.g., Entry error, extension from supplier...",
        "التاريخ مطلوب": "Date is required",
        "السبب مطلوب": "Reason is required",
        "تحديث": "Update",
        "السابق": "Previous",
        "التالي": "Next",
        "صفحة": "Page",
        "من": "of",
        "إجمالي": "Total",
        "تأكيد الحذف": "Confirm Delete",
        "سيتم حذف الفاتورة وإرجاع المخزون.": "The invoice will be deleted and stock will be returned.",
        "نعم، حذف": "Yes, delete",
        "تم الحذف": "Deleted",
        "فشل الحذف": "Delete failed",
        "جاري التحميل...": "Loading...",
        "عميل نقدي": "Cash Customer",
        "فشل تحميل الفاتورة": "Failed to load invoice",
        "فاتورة رقم": "Invoice No.",
        "المتجر:": "Store:",
        "شكراً لتعاملكم معنا.": "Thank you for dealing with us.",
        "إرسال الفاتورة (PDF)": "Send Invoice (PDF)",
        "وظيفة إرسال البريد غير متوفرة": "Mail sending function unavailable",
        "فشل تجهيز الفاتورة": "Failed to prepare invoice",
        "الرجاء إدخال المبلغ": "Please enter the amount",
        "تم فتح الصندوق": "Box opened",
        "حدث خطأ أثناء الفتح": "Error occurred during opening",
        "لا يوجد صندوق مفتوح حالياً": "No open box currently",
        "الرجاء إدخال المبلغ الموجود فعليياً": "Please enter the actual amount",
        "هل أنت متأكد؟": "Are you sure?",
        "سيتم إغلاق الوردية.": "The shift will be closed.",
        "نعم، إغلاق": "Yes, close",
        "تراجع": "Back",
        "مطابقة ممتازة ✅": "Perfect match ✅",
        "عجز:": "Deficit:",
        "زيادة:": "Surplus:",
        "تم الإغلاق": "Closed",
        "خطأ في السيرفر (500)": "Server Error (500)",
        "اختر العميل (اختياري)": "Select customer (Optional)",
        "ابحث عن المنتج (اسم أو باركود)...": "Search for product (name or barcode)...",
        "جاري البحث...": "Searching...",
        "لا توجد فواتير لهذا المنتج/العميل": "No invoices for this product/customer",
        "↩️ إرجاع": "↩️ Return",
        "⛔ منتج منتهي الصلاحية!": "⛔ Product Expired!",
        "حفاظاً على السلامة، لا يمكن بيع هذا المنتج.": "For safety, this product cannot be sold.",
        "📝 تحديث التاريخ (على مسؤوليتي)": "📝 Update date (at my own risk)",
        "إلغاء البيع": "Cancel sale",
        "تنبيه صلاحية": "Expiry Alert",
        "تحديث الصلاحية وتوثيق العملية": "Update expiry and document the process",
        "تاريخ الانتهاء الجديد:": "New Expiry Date:",
        "سبب التعديل (إلزامي للتوثيق):": "Modification reason (mandatory):",
        "اكتب السبب بوضوح ليظهر في تقرير الإدارة...": "Write the reason clearly to appear in the management report...",
        "حفظ التعديل والبيع": "Save modification and sell",
        "الرجاء إدخال التاريخ وسبب مقنع (5 أحرف على الأقل)": "Please enter the date and a valid reason (at least 5 characters)",
        "تم التوثيق!": "Documented!",
        "حدث خطأ في النظام": "System error occurred",
        "جاري التجهيز...": "Preparing...",
        "يرجى الانتظار بينما يتم تجهيز ملف التقرير...": "Please wait while the report file is being prepared...",
        "تحية طيبة،": "Best regards,",
        "نرفق لكم تقرير سجل المبيعات الخاص بـ": "Attached is the sales record report for",
        "تفاصيل التقرير:": "Report Details:",
        "تاريخ التقرير:": "Report Date:",
        "حالة الدفع المختارة:": "Selected Payment Status:",
        "مرفق لكم التقرير التفصيلي كملف PDF يحتوي على كافة العمليات المالية.": "Attached is the detailed report as a PDF containing all financial transactions.",
        "شكراً لثقتكم بنا،": "Thank you for your trust,",
        "إدارة المبيعات - نظام Tech-Sys": "Sales Management - Tech-Sys System",
        "تقرير سجل المبيعات -": "Sales Record Report -",
        "حدث خطأ: وظيفة إرسال البريد غير متوفرة": "Error: Mail sending function unavailable",
        "فشل تجهيز ملف التقرير": "Failed to prepare report file",
        "حدث خطأ أثناء التواصل مع السيرفر": "Error communicating with server",
        "جاري تجهيز ملف التقرير...": "Preparing report file...",
        "يرجى الانتظار قليلاً لجمع البيانات وتكوين ملف PDF...": "Please wait a while to collect data and generate the PDF file...",
        "إرسال سجل المبيعات كمرفق PDF": "Send sales record as PDF attachment",
        "حدث خطأ: وظيفة إرسال الواتساب غير متوفرة": "Error: WhatsApp sending function unavailable",
        "تم إرجاع جميع الأصناف - لا توجد أصناف متبقية": "All items returned - no items remaining",
        "لا توجد مرتجعات مسجلة": "No recorded returns",
        "فشل تحميل بيانات المرتجعات": "Failed to load returns data",
        "تقرير المرتجعات": "Returns Report",
        "جاري تجهيز ملف PDF...": "Preparing PDF file...",
        "يرجى الانتظار قليلاً...": "Please wait a while...",
        "تقرير مرتجعات -": "Returns report -",
        "يرجى الاطلاع على الملف المرفق.": "Please see the attached file.",
        "تقرير المرتجعات PDF": "Returns Report PDF",
        "فشل إنشاء ملف PDF": "Failed to create PDF file",
        "لا توجد أصناف": "No items",
        "إرسال الفاتورة رقم #": "Send Invoice No. #",
        "نواقص المخزون": "Stock Shortages",
        "منتجات منتهية/قريبة": "Expired/Near expiry",
        "لوحة تحكم المتجر:": "Store Dashboard:",
        "أهلاً بك في متجرك!": "Welcome to your store!",
        "نقطة البيع (POS)": "Point of Sale (POS)",
        "(الكاشير)": "(Cashier)",
        "إجمالي قائمة الطعام (المنيو)": "Total Menu Items",
        "باقي": "Remaining",
        "حد التنبيه": "Alert Limit",
        "المتبقي": "Remaining"
    }
    
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    for ar_key, en_val in mapping.items():
        if ar_key in data:
            data[ar_key] = en_val
            
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    
    print(f"Translated {len(mapping)} keys in {os.path.basename(file_path)}")

if __name__ == "__main__":
    translate_en_json(r'c:\xampp\htdocs\system\resources\lang\en.json')
