import json
import os

translations = {
    "en": {
        "إدارة المنتجات": "Product Management",
        "إضافة منتج جديد": "Add New Product",
        "إجمالي المنتجات": "Total Products",
        "مخزون منخفض": "Low Stock",
        "نافذ (0 كمية)": "Out of Stock (0 Qty)",
        "التصنيف": "Category",
        "اختر التصنيفات": "Select Categories",
        "كل الحالات": "All Statuses",
        "منتجات فعالة": "Active Products",
        "منتجات معطلة": "Inactive Products",
        "الأعمدة": "Columns",
        "بحث...": "Search...",
        "صورة": "Image",
        "المنتج": "Product",
        "الباركود": "Barcode",
        "الوحدة": "Unit",
        "التكلفة": "Cost",
        "سعر البيع": "Selling Price",
        "الربح": "Profit",
        "المخزون": "Stock",
        "الحالة": "Status",
        "إجراءات": "Actions",
        "أحجام/وحدات تقديم": "Sizes/Serving Units",
        "وحدات إضافية": "Additional Units",
        "شامل": "Inclusive",
        "غير قابل للبيع": "Not for Sale",
        "فعال": "Active",
        "معطل": "Inactive",
        "حذف؟": "Delete?",
        "تفاصيل الوحدات الإضافية": "Additional Units Details",
        "التحويل": "Conversion",
        "سعر البيع (شامل الضريبة)": "Selling Price (Inc. Tax)",
        "المخزون المتوفر": "Available Stock",
        "لا توجد بيانات": "No data found"
    },
    "fr": {
        "إدارة المنتجات": "Gestion des produits",
        "إضافة منتج جديد": "Ajouter un nouveau produit",
        "إجمالي المنتجات": "Total des produits",
        "مخزون منخفض": "Stock faible",
        "نافذ (0 كمية)": "Rupture de stock (0 Qté)",
        "التصنيف": "Catégorie",
        "اختر التصنيفات": "Choisir les catégories",
        "كل الحالات": "Tous les statuts",
        "منتجات فعالة": "Produits actifs",
        "منتجات معطلة": "Produits inactifs",
        "الأعمدة": "Colonnes",
        "بحث...": "Recherche...",
        "صورة": "Image",
        "المنتج": "Produit",
        "الباركود": "Code-barres",
        "الوحدة": "Unité",
        "التكلفة": "Coût",
        "سعر البيع": "Prix de vente",
        "الربح": "Profit",
        "المخزون": "Stock",
        "الحالة": "Statut",
        "إجراءات": "Actions",
        "أحجام/وحدات تقديم": "Tailles/Unités de service",
        "وحدات إضافية": "Unités supplémentaires",
        "شامل": "TTC",
        "غير قابل للبيع": "Non vendable",
        "فعال": "Actif",
        "معطل": "Désactivé",
        "حذف؟": "Supprimer ?",
        "تفاصيل الوحدات الإضافية": "Détails des unités supplémentaires",
        "التحويل": "Conversion",
        "سعر البيع (شامل الضريبة)": "Prix de vente (TTC)",
        "المخزون المتوفر": "Stock disponible",
        "لا توجد بيانات": "Aucune donnée trouvée"
    },
    "de": {
        "إدارة المنتجات": "Produktmanagement",
        "إضافة منتج جديد": "Neues Produkt hinzufügen",
        "إجمالي المنتجات": "Produkte insgesamt",
        "مخزون منخفض": "Niedriger Lagerbestand",
        "نافذ (0 كمية)": "Nicht vorrätig (0 Menge)",
        "التصنيف": "Kategorie",
        "اختر التصنيفات": "Kategorien auswählen",
        "كل الحالات": "Alle Status",
        "منتجات فعالة": "Aktive Produkte",
        "منتجات معطلة": "Inaktive Produkte",
        "الأعمدة": "Spalten",
        "بحث...": "Suchen...",
        "صورة": "Bild",
        "المنتج": "Produkt",
        "الباركود": "Barcode",
        "الوحدة": "Einheit",
        "التكلفة": "Kosten",
        "سعر البيع": "Verkaufspreis",
        "الربح": "Profit",
        "المخزون": "Lagerbestand",
        "الحالة": "Status",
        "إجراءات": "Aktionen",
        "أحجام/وحدات تقديم": "Größen/Serviereinheiten",
        "وحدات إضافية": "Zusätzliche Einheiten",
        "شامل": "Inklusive",
        "غير قابل للبيع": "Nicht zum Verkauf",
        "فعال": "Aktiv",
        "معطل": "Inaktiv",
        "حذف؟": "Löschen?",
        "تفاصيل الوحدات الإضافية": "Zusätzliche Einheiten Details",
        "التحويل": "Umwandlung",
        "سعر البيع (شامل الضريبة)": "Verkaufspreis (inkl. MwSt.)",
        "المخزون المتوفر": "Verfügbarer Lagerbestand",
        "لا توجد بيانات": "Keine Daten gefunden"
    },
    "ru": {
        "إدارة المنتجات": "Управление продуктами",
        "إضافة منتج جديد": "Добавить новый продукт",
        "إجمالي المنتجات": "Всего товаров",
        "مخزون منخفض": "Низкий запас",
        "نافذ (0 كمية)": "Нет в наличии (0 кол-во)",
        "التصنيف": "Категория",
        "اختر التصنيفات": "Выбрать категории",
        "كل الحالات": "Все статусы",
        "منتجات فعالة": "Активные товары",
        "منتجات معطلة": "Неактивные товары",
        "الأعمدة": "Столбцы",
        "بحث...": "Поиск...",
        "صورة": "Изображение",
        "المنتج": "Товар",
        "الباركود": "Штрих-код",
        "الوحدة": "Единица",
        "التكلفة": "Цена закупки",
        "سعر البيع": "Цена продажи",
        "الربح": "Прибыль",
        "المخزون": "Склад",
        "الحالة": "Статус",
        "إجراءات": "Действия",
        "أحجام/وحدات تقديم": "Размеры/Единицы",
        "وحدات إضافية": "Доп. единицы",
        "شامل": "Включая",
        "غير قابل للبيع": "Не для продажи",
        "فعال": "Активен",
        "معطل": "Неактивен",
        "حذف؟": "Удалить?",
        "تفاصيل الوحدات الإضافية": "Детали доп. единиц",
        "التحويل": "Конверсия",
        "سعر البيع (شامل الضريبة)": "Цена продажи (с налогом)",
        "المخزون المتوفر": "Доступный запас",
        "لا توجد بيانات": "Данные не найдены"
    },
    "pt": {
        "إدارة المنتجات": "Gestão de Produtos",
        "إضافة منتج جديد": "Adicionar Novo Produto",
        "إجمالي المنتجات": "Total de Produtos",
        "مخزون منخفض": "Stock Baixo",
        "نافذ (0 كمية)": "Esgotado (0 Qtd)",
        "التصنيف": "Categoria",
        "اختر التصنيفات": "Selecionar Categorias",
        "كل الحالات": "Todos os Status",
        "منتجات فعالة": "Produtos Ativos",
        "منتجات معطلة": "Produtos Inativos",
        "الأعمدة": "Colunas",
        "بحث...": "Pesquisar...",
        "صورة": "Imagem",
        "المنتج": "Produto",
        "الباركود": "Código de Barras",
        "الوحدة": "Unidade",
        "التكلفة": "Custo",
        "سعر البيع": "Preço de Venda",
        "الربح": "Lucro",
        "المخزون": "Stock",
        "الحالة": "Status",
        "إجراءات": "Ações",
        "أحجام/وحدات تقديم": "Tamanhos/Unid. Serviço",
        "وحدات إضافية": "Unidades Adicionais",
        "شامل": "Inclusivo",
        "غير قابل للبيع": "Não está à venda",
        "فعال": "Ativo",
        "معطل": "Inativo",
        "حذف؟": "Excluir?",
        "تفاصيل الوحدات الإضافية": "Detalhes Unid. Adicionais",
        "التحويل": "Conversão",
        "سعر البيع (شامل الضريبة)": "Preço de Venda (com Imposto)",
        "المخزون المتوفر": "Stock Disponível",
        "لا توجد بيانات": "Nenhum dado encontrado"
    },
    "pt-BR": {
        "إدارة المنتجات": "Gestão de Produtos",
        "إضافة منتج جديد": "Adicionar Novo Produto",
        "إجمالي المنتجات": "Total de Produtos",
        "مخزون منخفض": "Estoque Baixo",
        "نافذ (0 كمية)": "Esgotado (0 Qtd)",
        "التصنيف": "Categoria",
        "اختر التصنيفات": "Selecionar Categorias",
        "كل الحالات": "Todos os Status",
        "منتجات فعالة": "Produtos Ativos",
        "منتجات معطلة": "Produtos Inativos",
        "الأعمدة": "Colunas",
        "بحث...": "Pesquisar...",
        "صورة": "Imagem",
        "المنتج": "Produto",
        "الباركود": "Código de Barras",
        "الوحدة": "Unidade",
        "التكلفة": "Custo",
        "سعر البيع": "Preço de Venda",
        "الربح": "Lucro",
        "المخزون": "Estoque",
        "الحالة": "Status",
        "إجراءات": "Ações",
        "أحجام/وحدات تقديم": "Tamanhos/Unid. Serviço",
        "وحدات إضافية": "Unidades Adicionais",
        "شامل": "Inclusivo",
        "غير قابل للبيع": "Não está à venda",
        "فعال": "Ativo",
        "معطل": "Inativo",
        "حذف؟": "Excluir?",
        "تفاصيل الوحدات الإضافية": "Detalhes Unid. Adicionais",
        "التحويل": "Conversão",
        "سعر البيع (شامل الضريبة)": "Preço de Venda (com Imposto)",
        "المخزون المتوفر": "Estoque Disponível",
        "لا توجد بيانات": "Nenhum dado encontrado"
    },
    "hr": {
        "إدارة المنتجات": "Upravljanje proizvodima",
        "إضافة منتج جديد": "Dodaj novi proizvod",
        "إجمالي المنتجات": "Ukupno proizvoda",
        "مخزون منخفض": "Niska zaliha",
        "نافذ (0 كمية)": "Nema na zalihi (0 kol)",
        "التصنيف": "Kategorija",
        "اختر التصنيفات": "Odaberite kategorije",
        "كل الحالات": "Svi statusi",
        "منتجات فعالة": "Aktivni proizvodi",
        "منتجات معطلة": "Neaktivni proizvodi",
        "الأعمدة": "Stupci",
        "بحث...": "Traži...",
        "صورة": "Slika",
        "المنتج": "Proizvod",
        "الباركود": "Barkod",
        "الوحدة": "Jedinica",
        "التكلفة": "Trošak",
        "سعر البيع": "Prodajna cijena",
        "الربح": "Dobit",
        "المخزون": "Zaliha",
        "الحالة": "Status",
        "إجراءات": "Akcije",
        "أحجام/وحدات تقديم": "Veličine/Jedinice posluživanja",
        "وحدات إضافية": "Dodatne jedinice",
        "شامل": "Uključujući",
        "غير قابل للبيع": "Nije za prodaju",
        "فعال": "Aktivno",
        "معطل": "Neaktivno",
        "حذف؟": "Obriši?",
        "تفاصيل الوحدات الإضافية": "Pojedinosti dodatnih jedinica",
        "التحويل": "Konverzija",
        "سعر البيع (شامل الضريبة)": "Prodajna cijena (uklj. porez)",
        "المخزون المتوفر": "Dostupna zaliha",
        "لا توجد بيانات": "Nema podataka"
    }
}

lang_dir = r'c:\xampp\htdocs\system\resources\lang'

for lang, mapping in translations.items():
    file_path = os.path.join(lang_dir, lang + ".json")
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
            except:
                data = {}
        
        updated = False
        for ar_key, trans_val in mapping.items():
            data[ar_key] = trans_val
            updated = True
            
        if updated:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)
            print(f"Updated {lang}.json with {len(mapping)} translations.")
