import json
import os

langs = {
    "ar": {
        "owner_withdrawals_report_title": "تقرير مسحوبات المالك",
        "total_cost_capital_purchase_price": "إجمالي التكلفة (رأس المال - سعر الشراء)",
        "total_selling_price_display": "إجمالي سعر البيع (Selling Price)",
        "withdrawal_number": "رقم المسحوب",
        "items_count_lbl": "عدد المواد",
        "unit_cost_lbl": "التكلفة (للوحدة)",
        "total_cost_lbl": "إجمالي التكلفة",
        "selling_price_lbl": "سعر البيع",
        "total_sale_lbl": "الإجمالي (سعر البيع)",
        "withdrawal_details_title": "تفاصيل المسحوبات",
        "withdrawal_number_val": "مسحوبات رقم",
        "confirm_return_withdrawal": "هل أنت متأكد من إرجاع هذه المسحوبات؟ سيتم حذف العملية وإرجاع المواد للمخزون.",
        "failed_return_withdrawal": "فشل في إرجاع المسحوبات",
        "preparing_withdrawals_report": "جاري تجهيز تقرير المسحوبات...",
        "withdrawals_report_whatsapp_text": "*تقرير مسحوبات المالك*\n",
        "attached_detailed_withdrawals_report": "مرفق لكم تقرير مسحوبات المالك التفصيلي.",
        "send_withdrawals_pdf_attachment": "إرسال تقرير المسحوبات كمرفق PDF"
    },
    "en": {
        "owner_withdrawals_report_title": "Store Owner Withdrawals",
        "total_cost_capital_purchase_price": "Total Cost (Capital - Purchase Price)",
        "total_selling_price_display": "Total Selling Price",
        "withdrawal_number": "Withdrawal Number",
        "items_count_lbl": "Items Count",
        "unit_cost_lbl": "Unit Cost",
        "total_cost_lbl": "Total Cost",
        "selling_price_lbl": "Selling Price",
        "total_sale_lbl": "Total (Selling Price)",
        "withdrawal_details_title": "Withdrawal Details",
        "withdrawal_number_val": "Withdrawal No.",
        "confirm_return_withdrawal": "Are you sure you want to return this withdrawal? The process will be deleted and items returned to stock.",
        "failed_return_withdrawal": "Failed to return the withdrawal.",
        "preparing_withdrawals_report": "Preparing withdrawals report...",
        "withdrawals_report_whatsapp_text": "*Owner Withdrawals Report*\n",
        "attached_detailed_withdrawals_report": "Attached is the detailed owner withdrawals report.",
        "send_withdrawals_pdf_attachment": "Send Withdrawals Report as PDF"
    },
    "fr": {
        "owner_withdrawals_report_title": "Retraits du Proprietaire",
        "total_cost_capital_purchase_price": "Coût Total (Capital - Prix d'Achat)",
        "total_selling_price_display": "Prix de Vente Total",
        "withdrawal_number": "Numéro de Retrait",
        "items_count_lbl": "Nombre d'Articles",
        "unit_cost_lbl": "Coût Unitaire",
        "total_cost_lbl": "Coût Total",
        "selling_price_lbl": "Prix de Vente",
        "total_sale_lbl": "Total (Prix de Vente)",
        "withdrawal_details_title": "Détails du Retrait",
        "withdrawal_number_val": "Retrait N°",
        "confirm_return_withdrawal": "Êtes-vous sûr de vouloir retourner ce retrait ? Le processus sera supprimé et les articles seront remis en stock.",
        "failed_return_withdrawal": "Échec du retour du retrait.",
        "preparing_withdrawals_report": "Préparation du rapport des retraits...",
        "withdrawals_report_whatsapp_text": "*Rapport des Retraits du Propriétaire*\n",
        "attached_detailed_withdrawals_report": "Veuillez trouver ci-joint le rapport détaillé des retraits du propriétaire.",
        "send_withdrawals_pdf_attachment": "Envoyer le rapport des retraits en PDF"
    },
    "es": {
        "owner_withdrawals_report_title": "Retiros del Propietario",
        "total_cost_capital_purchase_price": "Costo Total (Capital - Precio de Compra)",
        "total_selling_price_display": "Precio Total de Venta",
        "withdrawal_number": "Número de Retiro",
        "items_count_lbl": "Cantidad de Artículos",
        "unit_cost_lbl": "Costo Unitario",
        "total_cost_lbl": "Costo Total",
        "selling_price_lbl": "Precio de Vente",
        "total_sale_lbl": "Total (Precio de Venta)",
        "withdrawal_details_title": "Detalles del Retiro",
        "withdrawal_number_val": "Retiro N°",
        "confirm_return_withdrawal": "¿Está seguro de querer devolver este retiro? El proceso será eliminado y los artículos devueltos al inventario.",
        "failed_return_withdrawal": "Fallo al devolver el retiro.",
        "preparing_withdrawals_report": "Preparando el informe de retiros...",
        "withdrawals_report_whatsapp_text": "*Informe de Retiros del Propietario*\n",
        "attached_detailed_withdrawals_report": "Adjunto encontrará el informe detallado de retiros del propietario.",
        "send_withdrawals_pdf_attachment": "Enviar Informe de Retiros en PDF"
    },
    "de": {
        "owner_withdrawals_report_title": "Inhaberentnahmen",
        "total_cost_capital_purchase_price": "Gesamtkosten (Kapital - Kaufpreis)",
        "total_selling_price_display": "Gesamtverkaufspreis",
        "withdrawal_number": "Entnahmenummer",
        "items_count_lbl": "Artikelanzahl",
        "unit_cost_lbl": "Stückkosten",
        "total_cost_lbl": "Gesamtkosten",
        "selling_price_lbl": "Verkaufspreis",
        "total_sale_lbl": "Gesamt (Verkaufspreis)",
        "withdrawal_details_title": "Entnahmedetails",
        "withdrawal_number_val": "Entnahme Nr.",
        "confirm_return_withdrawal": "Sind Sie sicher, dass Sie diese Entnahme stornieren möchten? Der Vorgang wird gelöscht und die Artikel dem Bestand zurückgebucht.",
        "failed_return_withdrawal": "Stornierung der Entnahme fehlgeschlagen.",
        "preparing_withdrawals_report": "Entnahmebericht wird vorbereitet...",
        "withdrawals_report_whatsapp_text": "*Inhaberentnahmebericht*\n",
        "attached_detailed_withdrawals_report": "Anbei finden Sie den detaillierten Bericht über die Inhaberentnahmen.",
        "send_withdrawals_pdf_attachment": "Entnahmebericht als PDF senden"
    },
    "tr": {
        "owner_withdrawals_report_title": "Mağaza Sahibi Çekimleri",
        "total_cost_capital_purchase_price": "Toplam Maliyet (Sermaye - Alış Fiyatı)",
        "total_selling_price_display": "Toplam Satış Fiyatı",
        "withdrawal_number": "Çekim Numarası",
        "items_count_lbl": "Ürün Sayısı",
        "unit_cost_lbl": "Birim Maliyeti",
        "total_cost_lbl": "Toplam Maliyet",
        "selling_price_lbl": "Satış Fiyatı",
        "total_sale_lbl": "Toplam (Satış Fiyatı)",
        "withdrawal_details_title": "Çekim Detayları",
        "withdrawal_number_val": "Çekim No.",
        "confirm_return_withdrawal": "Bu çekimi iptal etmek istediğinize emin misiniz? İşlem silinecek ve ürünler stoğa iade edilecektir.",
        "failed_return_withdrawal": "Çekim iptal edilemedi.",
        "preparing_withdrawals_report": "Çekim raporu hazırlanıyor...",
        "withdrawals_report_whatsapp_text": "*Mağaza Sahibi Çekimleri Raporu*\n",
        "attached_detailed_withdrawals_report": "Detaylı mağaza sahibi çekimleri raporu ektedir.",
        "send_withdrawals_pdf_attachment": "Çekim Raporunu PDF Olarak Gönder"
    },
    "ru": {
        "owner_withdrawals_report_title": "Изъятия Владельца",
        "total_cost_capital_purchase_price": "Общая Стоимость (Капитал - Закупочная Цена)",
        "total_selling_price_display": "Общая Цена Продажи",
        "withdrawal_number": "Номер Изъятия",
        "items_count_lbl": "Количество Позиций",
        "unit_cost_lbl": "Стоимость Единицы",
        "total_cost_lbl": "Общая Стоимость",
        "selling_price_lbl": "Цена Продажи",
        "total_sale_lbl": "Итого (Цена Продажи)",
        "withdrawal_details_title": "Детали Изъятия",
        "withdrawal_number_val": "Изъятие №",
        "confirm_return_withdrawal": "Вы уверены, что хотите отменить это изъятие? Операция будет удалена, а товары возвращены на склад.",
        "failed_return_withdrawal": "Не удалось отменить изъятие.",
        "preparing_withdrawals_report": "Подготовка отчета об изъятиях...",
        "withdrawals_report_whatsapp_text": "*Отчет об Изъятиях Владельца*\n",
        "attached_detailed_withdrawals_report": "Во вложении подробный отчет об изъятиях владельца.",
        "send_withdrawals_pdf_attachment": "Отправить Отчет об Изъятиях в PDF"
    },
    "pt": {
        "owner_withdrawals_report_title": "Saques do Proprietário",
        "total_cost_capital_purchase_price": "Custo Total (Capital - Preço de Compra)",
        "total_selling_price_display": "Preço Total de Venda",
        "withdrawal_number": "Número do Saque",
        "items_count_lbl": "Quantidade de Itens",
        "unit_cost_lbl": "Custo Unitário",
        "total_cost_lbl": "Custo Total",
        "selling_price_lbl": "Preço de Venda",
        "total_sale_lbl": "Total (Preço de Venda)",
        "withdrawal_details_title": "Detalhes do Saque",
        "withdrawal_number_val": "Saque Nº",
        "confirm_return_withdrawal": "Tem certeza que deseja devolver este saque? O processo será excluído e os itens retornarão ao estoque.",
        "failed_return_withdrawal": "Falha ao devolver o saque.",
        "preparing_withdrawals_report": "Preparando relatório de saques...",
        "withdrawals_report_whatsapp_text": "*Relatório de Saques do Proprietário*\n",
        "attached_detailed_withdrawals_report": "Anexo o relatório detalhado de saques do proprietário.",
        "send_withdrawals_pdf_attachment": "Enviar Relatório de Saques em PDF"
    },
    "pt-BR": {
        "owner_withdrawals_report_title": "Saques do Proprietário",
        "total_cost_capital_purchase_price": "Custo Total (Capital - Preço de Compra)",
        "total_selling_price_display": "Preço Total de Venda",
        "withdrawal_number": "Número do Saque",
        "items_count_lbl": "Quantidade de Itens",
        "unit_cost_lbl": "Custo Unitário",
        "total_cost_lbl": "Custo Total",
        "selling_price_lbl": "Preço de Venda",
        "total_sale_lbl": "Total (Preço de Venda)",
        "withdrawal_details_title": "Detalhes do Saque",
        "withdrawal_number_val": "Saque Nº",
        "confirm_return_withdrawal": "Tem certeza que deseja devolver este saque? O processo será excluído e os itens retornarão ao estoque.",
        "failed_return_withdrawal": "Falha ao devolver o saque.",
        "preparing_withdrawals_report": "Preparando relatório de saques...",
        "withdrawals_report_whatsapp_text": "*Relatório de Saques do Proprietário*\n",
        "attached_detailed_withdrawals_report": "Anexo o relatório detalhado de saques do proprietário.",
        "send_withdrawals_pdf_attachment": "Enviar Relatório de Saques em PDF"
    },
    "hr": {
        "owner_withdrawals_report_title": "Povlačenja Vlasnika",
        "total_cost_capital_purchase_price": "Ukupni Trošak (Kapital - Nabavna Cijena)",
        "total_selling_price_display": "Ukupna Prodajna Cijena",
        "withdrawal_number": "Broj Povlačenja",
        "items_count_lbl": "Broj Stavki",
        "unit_cost_lbl": "Jedinični Trošak",
        "total_cost_lbl": "Ukupni Trošak",
        "selling_price_lbl": "Prodajna Cijena",
        "total_sale_lbl": "Ukupno (Prodajna Cijena)",
        "withdrawal_details_title": "Detalji Povlačenja",
        "withdrawal_number_val": "Povlačenje Br.",
        "confirm_return_withdrawal": "Jeste li sigurni da želite poništiti ovo povlačenje? Postupak će biti izbrisan, a artikli vraćeni na zalihu.",
        "failed_return_withdrawal": "Poništavanje povlačenja nije uspjelo.",
        "preparing_withdrawals_report": "Priprema izvješća o povlačenjima...",
        "withdrawals_report_whatsapp_text": "*Izvješće o Povlačenjima Vlasnika*\n",
        "attached_detailed_withdrawals_report": "U privitku je detaljno izvješće o povlačenjima vlasnika.",
        "send_withdrawals_pdf_attachment": "Pošalji Izvješće o Povlačenjima kao PDF"
    },
    "ja": {
        "owner_withdrawals_report_title": "オーナー引き出しレポート",
        "total_cost_capital_purchase_price": "総原価（資本 - 仕入価格）",
        "total_selling_price_display": "総販売価格",
        "withdrawal_number": "引き出し番号",
        "items_count_lbl": "アイテム数",
        "unit_cost_lbl": "単価",
        "total_cost_lbl": "総原価",
        "selling_price_lbl": "販売価格",
        "total_sale_lbl": "合計（販売価格）",
        "withdrawal_details_title": "引き出し詳細",
        "withdrawal_number_val": "引き出し番号",
        "confirm_return_withdrawal": "この引き出しを返品してもよろしいですか？処理は削除され、アイテムは在庫に戻されます。",
        "failed_return_withdrawal": "引き出しの返品に失敗しました。",
        "preparing_withdrawals_report": "引き出しレポートを準備中...",
        "withdrawals_report_whatsapp_text": "*オーナー引き出しレポート*\n",
        "attached_detailed_withdrawals_report": "詳細なオーナー引き出しレポートが添付されています。",
        "send_withdrawals_pdf_attachment": "引き出しレポートをPDFで送信"
    },
    "zh": {
        "owner_withdrawals_report_title": "店主提款记录",
        "total_cost_capital_purchase_price": "总成本 (资本 - 采购价)",
        "total_selling_price_display": "总销售价",
        "withdrawal_number": "提款单号",
        "items_count_lbl": "项目数",
        "unit_cost_lbl": "单位成本",
        "total_cost_lbl": "总成本",
        "selling_price_lbl": "销售价",
        "total_sale_lbl": "总计 (销售价)",
        "withdrawal_details_title": "提款详情",
        "withdrawal_number_val": "提款单号",
        "confirm_return_withdrawal": "您确定要退回此提款单吗？流程将被删除，商品将退回库存。",
        "failed_return_withdrawal": "退回提款单失败。",
        "preparing_withdrawals_report": "正在准备提款报告...",
        "withdrawals_report_whatsapp_text": "*店主提款记录*\n",
        "attached_detailed_withdrawals_report": "随附详细的店主提款记录附件。",
        "send_withdrawals_pdf_attachment": "以PDF格式发送提款报告"
    }
}

for lang, mapping in langs.items():
    filepath = f"resources/lang/{lang}.json"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for k, v in mapping.items():
            data[k] = v
            
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        print(f"Updated {filepath} for owner withdrawals translations")

print("Finished syncing owner withdrawals translations.")
